const actions = {
  FETCH_EFFORTS_FOR_TRACING_REQUEST: "FETCH_EFFORTS_FOR_TRACING_REQUEST",
  FETCH_EFFORTS_FOR_TRACING_SUCCESS: "FETCH_EFFORTS_FOR_TRACING_SUCCESS",
  FETCH_EFFORTS_FOR_TRACING_ERROR: "FETCH_EFFORTS_FOR_TRACING_ERROR",

  ADD_EFFORTS_FOR_TRACING_REQUEST: "ADD_EFFORTS_FOR_TRACING_REQUEST",
  ADD_EFFORTS_FOR_TRACING_SUCCESS: "ADD_EFFORTS_FOR_TRACING_SUCCESS",
  ADD_EFFORTS_FOR_TRACING_ERROR: "ADD_EFFORTS_FOR_TRACING_ERROR",

  UPDATE_EFFORTS_FOR_TRACING_REQUEST: "UPDATE_EFFORTS_FOR_TRACING_REQUEST",
  UPDATE_EFFORTS_FOR_TRACING_SUCCESS: "UPDATE_EFFORTS_FOR_TRACING_SUCCESS",
  UPDATE_EFFORTS_FOR_TRACING_ERROR: "UPDATE_EFFORTS_FOR_TRACING_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addEffortsForTracingDetails: (url, body) => ({
    type: actions.ADD_EFFORTS_FOR_TRACING_REQUEST,
    payload: { url, body },
  }),

  updateEffortsForTracingDetails: (url, body) => ({
    type: actions.UPDATE_EFFORTS_FOR_TRACING_REQUEST,
    payload: { url, body },
  }),

  getEffortsForTracingList: (url) => ({
    type: actions.FETCH_EFFORTS_FOR_TRACING_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
