const actions = {
  GENDER_REQUEST: "GENDER_REQUEST",
  GENDER_SUCCESS: "GENDER_SUCCESS",
  GENDER_ERROR: "GENDER_ERROR",

  CASTE_REQUEST: "CASTE_REQUEST",
  CASTE_SUCCESS: "CASTE_SUCCESS",
  CASTE_ERROR: "CASTE_ERROR",

  NOTICETOSURETY_REQUEST: "NOTICETOSURETY_REQUEST",
  NOTICETOSURETY_SUCCESS: "NOTICETOSURETY_SUCCESS",
  NOTICETOSURETY_ERROR: "NOTICETOSURETY_ERROR",

  SUB_CASTE_REQUEST: "SUB_CASTE_REQUEST",
  SUB_CASTE_SUCCESS: "SUB_CASTE_SUCCESS",
  SUB_CASTE_ERROR: "SUB_CASTE_ERROR",

  NATIONALITY_REQUEST: "NATIONALITY_REQUEST",
  NATIONALITY_SUCCESS: "NATIONALITY_SUCCESS",
  NATIONALITY_ERROR: "NATIONALITY_ERROR",

  RELIGION_REQUEST: "RELIGION_REQUEST",
  RELIGION_SUCCESS: "RELIGION_SUCCESS",
  RELIGION_ERROR: "RELIGION_ERROR",

  OCCUPATION_REQUEST: "OCCUPATION_REQUEST",
  OCCUPATION_SUCCESS: "OCCUPATION_SUCCESS",
  OCCUPATION_ERROR: "OCCUPATION_ERROR",

  EDUCATIONAL_QUALIFICATION_REQUEST: "EDUCATIONAL_QUALIFICATION_REQUEST",
  EDUCATIONAL_QUALIFICATION_SUCCESS: "EDUCATIONAL_QUALIFICATION_SUCCESS",
  EDUCATIONAL_QUALIFICATION_ERROR: "EDUCATIONAL_QUALIFICATION_ERROR",

  STATE_DISTRICT_REQUEST: "STATE_DISTRICT_REQUEST",
  STATE_DISTRICT_SUCCESS: "STATE_DISTRICT_SUCCESS",
  STATE_DISTRICT_ERROR: "STATE_DISTRICT_ERROR",

  VILLAGE_PINCODE_REQUEST: "VILLAGE_PINCODE_REQUEST",
  VILLAGE_PINCODE_SUCCESS: "VILLAGE_PINCODE_SUCCESS",
  VILLAGE_PINCODE_ERROR: "VILLAGE_PINCODE_ERROR",

  MATERIAL_OBJECT_TYPE_REQUEST: "MATERIAL_OBJECT_TYPE_REQUEST",
  MATERIAL_OBJECT_TYPE_SUCCESS: "MATERIAL_OBJECT_TYPE_SUCCESS",
  MATERIAL_OBJECT_TYPE_ERROR: "MATERIAL_OBJECT_TYPE_ERROR",

  MATERIAL_OBJECT_SUBTYPE_REQUEST: "MATERIAL_OBJECT_SUBTYPE_REQUEST",
  MATERIAL_OBJECT_SUBTYPE_SUCCESS: "MATERIAL_OBJECT_SUBTYPE_SUCCESS",
  MATERIAL_OBJECT_SUBTYPE_ERROR: "MATERIAL_OBJECT_SUBTYPE_ERROR",

  STAFF_REQUEST: "STAFF_REQUEST",
  STAFF_SUCCESS: "STAFF_SUCCESS",
  STAFF_ERROR: "STAFF_ERROR",

  STAFF_ALL_REQUEST: "STAFF_ALL_REQUEST",
  STAFF_ALL_SUCCESS: "STAFF_ALL_SUCCESS",
  STAFF_ALL_ERROR: "STAFF_ALL_ERROR",

  UNIT_MAPPING_REQUEST: "UNIT_MAPPING_REQUEST",
  UNIT_MAPPING_SUCCESS: "UNIT_MAPPING_SUCCESS",
  UNIT_MAPPING_ERROR: "UNIT_MAPPING_ERROR",

  TS_HIERARCHY_REQUEST: "TS_HIERARCHY_REQUEST",
  TS_HIERARCHY_SUCCESS: "TS_HIERARCHY_SUCCESS",
  TS_HIERARCHY_ERROR: "TS_HIERARCHY_ERROR",

  EXPERT_ROLE_REQUEST: "EXPERT_ROLE_REQUEST",
  EXPERT_ROLE_SUCCESS: "EXPERT_ROLE_SUCCESS",
  EXPERT_ROLE_ERROR: "EXPERT_ROLE_ERROR",

  EXPERT_TEAM_ROLE_REQUEST: "EXPERT_TEAM_ROLE_REQUEST",
  EXPERT_TEAM_ROLE_SUCCESS: "EXPERT_TEAM_ROLE_SUCCESS",
  EXPERT_TEAM_ROLE_ERROR: "EXPERT_TEAM_ROLE_ERROR",

  WITNESS_TYPE_REQUEST: "WITNESS_TYPE_REQUEST",
  WITNESS_TYPE_SUCCESS: "WITNESS_TYPE_SUCCESS",
  WITNESS_TYPE_ERROR: "WITNESS_TYPE_ERROR",

  WITNESS_RELATION_REQUEST: "WITNESS_RELATION_REQUEST",
  WITNESS_RELATION_SUCCESS: "WITNESS_RELATION_SUCCESS",
  WITNESS_RELATION_ERROR: "WITNESS_RELATION_ERROR",

  WITNESS_STRENGTH_REQUEST: "WITNESS_STRENGTH_REQUEST",
  WITNESS_STRENGTH_SUCCESS: "WITNESS_STRENGTH_SUCCESS",
  WITNESS_STRENGTH_ERROR: "WITNESS_STRENGTH_ERROR",

  IDENTITY_TYPE_REQUEST: "IDENTITY_TYPE_REQUEST",
  IDENTITY_TYPE_SUCCESS: "IDENTITY_TYPE_SUCCESS",
  IDENTITY_TYPE_ERROR: "IDENTITY_TYPE_ERROR",

  CRIME_CLASSIFICATION_REQUEST: "CRIME_CLASSIFICATION_REQUEST",
  CRIME_CLASSIFICATION_SUCCESS: "CRIME_CLASSIFICATION_SUCCESS",
  CRIME_CLASSIFICATION_ERROR: "CRIME_CLASSIFICATION_ERROR",

  CRIME_SUB_CLASSIFICATION_REQUEST: "CRIME_SUB_CLASSIFICATION_REQUEST",
  CRIME_SUB_CLASSIFICATION_SUCCESS: "CRIME_SUB_CLASSIFICATION_SUCCESS",
  CRIME_SUB_CLASSIFICATION_ERROR: "CRIME_SUB_CLASSIFICATION_ERROR",

  RESIDENCY_TYPE_REQUEST: "RESIDENCY_TYPE_REQUEST",
  RESIDENCY_TYPE_SUCCESS: "RESIDENCY_TYPE_SUCCESS",
  RESIDENCY_TYPE_ERROR: "RESIDENCY_TYPE_ERROR",

  PERSON_TYPE_REQUEST: "PERSON_TYPE_REQUEST",
  PERSON_TYPE_SUCCESS: "PERSON_TYPE_SUCCESS",
  PERSON_TYPE_ERROR: "PERSON_TYPE_ERROR",

  RELATION_TYPE_REQUEST: "RELATION_TYPE_REQUEST",
  RELATION_TYPE_SUCCESS: "RELATION_TYPE_SUCCESS",
  RELATION_TYPE_ERROR: "RELATION_TYPE_ERROR",

  MODE_OF_INTEMATION_TYPE_REQUEST: "MODE_OF_INTEMATION_TYPE_REQUEST",
  MODE_OF_INTEMATION_TYPE_SUCCESS: "MODE_OF_INTEMATION_TYPE_SUCCESS",
  MODE_OF_INTEMATION_TYPE_ERROR: "MODE_OF_INTEMATION_TYPE_ERROR",

  EXPERT_TEAMS_TYPE_REQUEST: "EXPERT_TEAMS_TYPE_REQUEST",
  EXPERT_TEAMS_TYPE_SUCCESS: "EXPERT_TEAMS_TYPE_SUCCESS",
  EXPERT_TEAMS_TYPE_ERROR: "EXPERT_TEAMS_TYPE_ERROR",

  RANK_REQUEST: "RANK_REQUEST",
  RANK_SUCCESS: "RANK_SUCCESS",
  RANK_ERROR: "RANK_ERROR",

  COURTS_NAME_REQUEST: "COURTS_NAME_REQUEST",
  COURTS_NAME_SUCCESS: "COURTS_NAME_SUCCESS",
  COURTS_NAME_ERROR: "COURTS_NAME_ERROR",

  JAILS_NAME_REQUEST: "JAILS_NAME_REQUEST",
  JAILS_NAME_SUCCESS: "JAILS_NAME_SUCCESS",
  JAILS_NAME_ERROR: "JAILS_NAME_ERROR",

  STATES_NAME_REQUEST: "STATES_NAME_REQUEST",
  STATES_NAME_SUCCESS: "STATES_NAME_SUCCESS",
  STATES_NAME_ERROR: "STATES_NAME_ERROR",

  HIGH_COURT_DIRECTIONS_REQUEST: "HIGH_COURT_DIRECTIONS_REQUEST",
  HIGH_COURT_DIRECTIONS_SUCCESS: "HIGH_COURT_DIRECTIONS_SUCCESS",
  HIGH_COURT_DIRECTIONS_ERROR: "HIGH_COURT_DIRECTIONS_ERROR",

  WITNESS_CATEGORY_REQUEST: "WITNESS_CATEGORY_REQUEST",
  WITNESS_CATEGORY_SUCCESS: "WITNESS_CATEGORY_SUCCESS",
  WITNESS_CATEGORY_ERROR: "WITNESS_CATEGORY_ERROR",

  STATEMENT_RECORDED_BY_REQUEST: "STATEMENT_RECORDED_BY_REQUEST",
  STATEMENT_RECORDED_BY_SUCCESS: "STATEMENT_RECORDED_BY_SUCCESS",
  STATEMENT_RECORDED_BY_ERROR: "STATEMENT_RECORDED_BY_ERROR",

  POLICE_CUSTODY_REASONS_REQUEST: "POLICE_CUSTODY_REASONS_REQUEST",
  POLICE_CUSTODY_REASONS_SUCCESS: "POLICE_CUSTODY_REASONS_SUCCESS",
  POLICE_CUSTODY_REASONS_ERROR: "POLICE_CUSTODY_REASONS_ERROR",

  PLACE_OF_RECORDINGS_REQUEST: "PLACE_OF_RECORDINGS_REQUEST",
  PLACE_OF_RECORDINGS_SUCCESS: "PLACE_OF_RECORDINGS_SUCCESS",
  PLACE_OF_RECORDINGS_ERROR: "PLACE_OF_RECORDINGS_ERROR",

  APPREHENSION_TYPE_REQUEST: "APPREHENSION_TYPE_REQUEST",
  APPREHENSION_TYPE_SUCCESS: "APPREHENSION_TYPE_SUCCESS",
  APPREHENSION_TYPE_ERROR: "APPREHENSION_TYPE_ERROR",

  PLACE_OF_ARREST_TYPE_REQUEST: "PLACE_OF_ARREST_TYPE_REQUEST",
  PLACE_OF_ARREST_TYPE_SUCCESS: "PLACE_OF_ARREST_TYPE_SUCCESS",
  PLACE_OF_ARREST_TYPE_ERROR: "PLACE_OF_ARREST_TYPE_ERROR",

  DISTRICT_REQUEST: "DISTRICT_REQUEST",
  DISTRICT_SUCCESS: "DISTRICT_SUCCESS",
  DISTRICT_ERROR: "DISTRICT_ERROR",

  MAJOR_HEAD_REQUEST: "MAJOR_HEAD_REQUEST",
  MAJOR_HEAD_SUCCESS: "MAJOR_HEAD_SUCCESS",
  MAJOR_HEAD_ERROR: "MAJOR_HEAD_ERROR",

  MINOR_HEAD_REQUEST: "MINOR_HEAD_REQUEST",
  MINOR_HEAD_SUCCESS: "MINOR_HEAD_SUCCESS",
  MINOR_HEAD_ERROR: "MINOR_HEAD_ERROR",

  ROAD_ACCIDENT_REQUEST: "ROAD_ACCIDENT_REQUEST",
  ROAD_ACCIDENT_SUCCESS: "ROAD_ACCIDENT_SUCCESS",
  ROAD_ACCIDENT_ERROR: "ROAD_ACCIDENT_ERROR",

  BODY_TYPE_REQUEST: "BODY_TYPE_REQUEST",
  BODY_TYPE_SUCCESS: "BODY_TYPE_SUCCESS",
  BODY_TYPE_ERROR: "BODY_TYPE_ERROR",

  BEARD_REQUEST: "BEARD_REQUEST",
  BEARD_SUCCESS: "BEARD_SUCCESS",
  BEARD_ERROR: "BEARD_ERROR",

  HAIR_COLOR_REQUEST: "HAIR_COLOR_REQUEST",
  HAIR_COLOR_SUCCESS: "HAIR_COLOR_SUCCESS",
  HAIR_COLOR_ERROR: "HAIR_COLOR_ERROR",

  EYE_COLOR_REQUEST: "EYE_COLOR_REQUEST",
  EYE_COLOR_SUCCESS: "EYE_COLOR_SUCCESS",
  EYE_COLOR_ERROR: "EYE_COLOR_ERROR",

  COMPLEXION_REQUEST: "COMPLEXION_REQUEST",
  COMPLEXION_SUCCESS: "COMPLEXION_SUCCESS",
  COMPLEXION_ERROR: "COMPLEXION_ERROR",

  DEFORMITIES_REQUEST: "DEFORMITIES_REQUEST",
  DEFORMITIES_SUCCESS: "DEFORMITIES_SUCCESS",
  DEFORMITIES_ERROR: "DEFORMITIES_ERROR",

  MOLES_REQUEST: "MOLES_REQUEST",
  MOLES_SUCCESS: "MOLES_SUCCESS",
  MOLES_ERROR: "MOLES_ERROR",

  LANGUAGES_REQUEST: "LANGUAGES_REQUEST",
  LANGUAGES_SUCCESS: "LANGUAGES_SUCCESS",
  LANGUAGES_ERROR: "LANGUAGES_ERROR",

  MUSTACHES_REQUEST: "MUSTACHES_REQUEST",
  MUSTACHES_SUCCESS: "MUSTACHES_SUCCESS",
  MUSTACHES_ERROR: "MUSTACHES_ERROR",

  TEETH_REQUEST: "TEETH_REQUEST",
  TEETH_SUCCESS: "TEETH_SUCCESS",
  TEETH_ERROR: "TEETH_ERROR",

  HOSPITALS_REQUEST: "HOSPITALS_REQUEST",
  HOSPITALS_SUCCESS: "HOSPITALS_SUCCESS",
  HOSPITALS_ERROR: "HOSPITALS_ERROR",

  BODY_DISPOSAL_REQUEST: "BODY_DISPOSAL_REQUEST",
  BODY_DISPOSAL_SUCCESS: "BODY_DISPOSAL_SUCCESS",
  BODY_DISPOSAL_ERROR: "BODY_DISPOSAL_ERROR",

  EFFORTS_TRACING_REQUEST: "EFFORTS_TRACING_REQUEST",
  EFFORTS_TRACING_SUCCESS: "EFFORTS_TRACING_SUCCESS",
  EFFORTS_TRACING_ERROR: "EFFORTS_TRACING_ERROR",

  UNITS_REQUEST: "UNITS_REQUEST",
  UNITS_SUCCESS: "UNITS_SUCCESS",
  UNITS_ERROR: "UNITS_ERROR",

  EVIDENCE_COLLECTION_REQUEST: "EVIDENCE_COLLECTION_REQUEST",
  EVIDENCE_COLLECTION_SUCCESS: "EVIDENCE_COLLECTION_SUCCESS",
  EVIDENCE_COLLECTION_ERROR: "EVIDENCE_COLLECTION_ERROR",

  ACT_REQUEST: "ACT_REQUEST",
  ACT_SUCCESS: "ACT_SUCCESS",
  ACT_ERROR: "ACT_ERROR",

  CIS_ACT_REQUEST: "CIS_ACT_REQUEST",
  CIS_ACT_SUCCESS: "CIS_ACT_SUCCESS",
  CIS_ACT_ERROR: "CIS_ACT_ERROR",

  SECTION_REQUEST: "SECTION_REQUEST",
  SECTION_SUCCESS: "SECTION_SUCCESS",
  SECTION_ERROR: "SECTION_ERROR",

  DIRECTION_FROM_PS_REQUEST: "DIRECTION_FROM_PS_REQUEST",
  DIRECTION_FROM_PS_SUCCESS: "DIRECTION_FROM_PS_SUCCESS",
  DIRECTION_FROM_PS_ERROR: "DIRECTION_FROM_PS_ERROR",

  MANDAL_REQUEST: "MANDAL_REQUEST",
  MANDAL_SUCCESS: "MANDAL_SUCCESS",
  MANDAL_ERROR: "MANDAL_ERROR",

  VILLAGE_FROM_PSCODE_REQUEST: "VILLAGE_FROM_PSCODE_REQUEST",
  VILLAGE_FROM_PSCODE_SUCCESS: "VILLAGE_FROM_PSCODE_SUCCESS",
  VILLAGE_FROM_PSCODE_ERROR: "VILLAGE_FROM_PSCODE_ERROR",

  UNIT_FROM_DISTRICT_REQUEST: "UNIT_FROM_DISTRICT_REQUEST",
  UNIT_FROM_DISTRICT_SUCCESS: "UNIT_FROM_DISTRICT_SUCCESS",
  UNIT_FROM_DISTRICT_ERROR: "UNIT_FROM_DISTRICT_ERROR",

  COURTS_FROM_PSCODE_REQUEST: "COURTS_FROM_PSCODE_REQUEST",
  COURTS_FROM_PSCODE_SUCCESS: "COURTS_FROM_PSCODE_SUCCESS",
  COURTS_FROM_PSCODE_ERROR: "COURTS_FROM_PSCODE_ERROR",

  FSL_EXPERT_TYPE_REQUEST: "FSL_EXPERT_TYPE_REQUEST",
  FSL_EXPERT_TYPE_SUCCESS: "FSL_EXPERT_TYPE_SUCCESS",
  FSL_EXPERT_TYPE_ERROR: "FSL_EXPERT_TYPE_ERROR",

  FSL_QUESTIONNAIRIE_REQUEST: "FSL_QUESTIONNAIRIE_REQUEST",
  FSL_QUESTIONNAIRIE_SUCCESS: "FSL_QUESTIONNAIRIE_SUCCESS",
  FSL_QUESTIONNAIRIE_ERROR: "FSL_QUESTIONNAIRIE_ERROR",

  GET_IO_DETAILS_REQUEST: "GET_IO_DETAILS_REQUEST",
  GET_IO_DETAILS_SUCCESS: "GET_IO_DETAILS_SUCCESS",
  GET_IO_DETAILS_ERROR: "GET_IO_DETAILS_ERROR",

  getFSLExpertTypeList: (url) => ({
    type: actions.FSL_EXPERT_TYPE_REQUEST,
    payload: { url },
  }),

  getEvidenceCollectionList: (url) => ({
    type: actions.EVIDENCE_COLLECTION_REQUEST,
    payload: { url },
  }),

  getUnitsList: (url) => ({
    type: actions.UNITS_REQUEST,
    payload: { url },
  }),

  getEffortForTracingList: (url) => ({
    type: actions.EFFORTS_TRACING_REQUEST,
    payload: { url },
  }),

  getBodyDisposalList: (url) => ({
    type: actions.BODY_DISPOSAL_REQUEST,
    payload: { url },
  }),

  getHospitalsList: (url) => ({
    type: actions.HOSPITALS_REQUEST,
    payload: { url },
  }),

  getGendersList: (url) => ({
    type: actions.GENDER_REQUEST,
    payload: { url },
  }),

  getCasteList: (url) => ({
    type: actions.CASTE_REQUEST,
    payload: { url },
  }),

  getNoticetosuretyList: (url) => ({
    type: actions.NOTICETOSURETY_REQUEST,
    payload: { url },
  }),

  getSubCasteList: (url) => ({
    type: actions.SUB_CASTE_REQUEST,
    payload: { url },
  }),

  getNationalityList: (url) => ({
    type: actions.NATIONALITY_REQUEST,
    payload: { url },
  }),

  getReligionList: (url) => ({
    type: actions.RELIGION_REQUEST,
    payload: { url },
  }),

  getOccupationList: (url) => ({
    type: actions.OCCUPATION_REQUEST,
    payload: { url },
  }),

  getEducationQualificationList: (url) => ({
    type: actions.EDUCATIONAL_QUALIFICATION_REQUEST,
    payload: { url },
  }),

  getStateDistrictList: (url) => ({
    type: actions.STATE_DISTRICT_REQUEST,
    payload: { url },
  }),

  getDistrictVillage: (url) => ({
    type: actions.VILLAGE_PINCODE_REQUEST,
    payload: { url },
  }),

  getMaterialTypeList: (url) => ({
    type: actions.MATERIAL_OBJECT_TYPE_REQUEST,
    payload: { url },
  }),

  getMaterialSubTypeList: (url) => ({
    type: actions.MATERIAL_OBJECT_SUBTYPE_REQUEST,
    payload: { url },
  }),

  getStaffList: (url) => ({
    type: actions.STAFF_REQUEST,
    payload: { url },
  }),

  getAllStaffList: (url) => ({
    type: actions.STAFF_ALL_REQUEST,
    payload: { url },
  }),

  getUnitMapping: (url) => ({
    type: actions.UNIT_MAPPING_REQUEST,
    payload: { url },
  }),

  getTsHierarchy: (url) => ({
    type: actions.TS_HIERARCHY_REQUEST,
    payload: { url },
  }),

  getExpertList: (url) => ({
    type: actions.EXPERT_ROLE_REQUEST,
    payload: { url },
  }),

  getExpertRoleList: (url) => ({
    type: actions.EXPERT_TEAM_ROLE_REQUEST,
    payload: { url },
  }),

  getWitnessTypeList: (url) => ({
    type: actions.WITNESS_TYPE_REQUEST,
    payload: { url },
  }),

  getWitnessRelationList: (url) => ({
    type: actions.WITNESS_RELATION_REQUEST,
    payload: { url },
  }),

  getWitnessStrengthList: (url) => ({
    type: actions.WITNESS_STRENGTH_REQUEST,
    payload: { url },
  }),

  getIdentityTypeList: (url) => ({
    type: actions.IDENTITY_TYPE_REQUEST,
    payload: { url },
  }),

  getCrimeClassificationList: (url) => ({
    type: actions.CRIME_CLASSIFICATION_REQUEST,
    payload: { url },
  }),

  getFIRMasterList: (url) => ({
    type: actions.CRIME_SUB_CLASSIFICATION_REQUEST,
    payload: { url },
  }),

  getResidencyTypeList: (url) => ({
    type: actions.RESIDENCY_TYPE_REQUEST,
    payload: { url },
  }),

  getPersonTypeList: (url) => ({
    type: actions.PERSON_TYPE_REQUEST,
    payload: { url },
  }),

  getRelationTypeList: (url) => ({
    type: actions.RELATION_TYPE_REQUEST,
    payload: { url },
  }),

  getModeOfIntemationList: (url) => ({
    type: actions.MODE_OF_INTEMATION_TYPE_REQUEST,
    payload: { url },
  }),

  getExpertTeamsList: (url) => ({
    type: actions.EXPERT_TEAMS_TYPE_REQUEST,
    payload: { url },
  }),

  getRanks: (url) => ({
    type: actions.RANK_REQUEST,
    payload: { url },
  }),

  getCourtsName: (url) => ({
    type: actions.COURTS_NAME_REQUEST,
    payload: { url },
  }),

  getJailsName: (url) => ({
    type: actions.JAILS_NAME_REQUEST,
    payload: { url },
  }),

  getStatesName: (url) => ({
    type: actions.STATES_NAME_REQUEST,
    payload: { url },
  }),

  getHighCourtDirections: (url) => ({
    type: actions.HIGH_COURT_DIRECTIONS_REQUEST,
    payload: { url },
  }),

  getWitnessCategories: (url) => ({
    type: actions.WITNESS_CATEGORY_REQUEST,
    payload: { url },
  }),

  getStatementRecords: (url) => ({
    type: actions.STATEMENT_RECORDED_BY_REQUEST,
    payload: { url },
  }),

  getPoliceCustodyReasons: (url) => ({
    type: actions.POLICE_CUSTODY_REASONS_REQUEST,
    payload: { url },
  }),

  getPlaceOfRecordingsList: (url) => ({
    type: actions.PLACE_OF_RECORDINGS_REQUEST,
    payload: { url },
  }),

  getApprehensionTypes: (url) => ({
    type: actions.APPREHENSION_TYPE_REQUEST,
    payload: { url },
  }),

  getPlaceOfArrestList: (url) => ({
    type: actions.PLACE_OF_ARREST_TYPE_REQUEST,
    payload: { url },
  }),

  getDistrictList: (url) => ({
    type: actions.DISTRICT_REQUEST,
    payload: { url },
  }),

  getMajorHeadList: (url) => ({
    type: actions.MAJOR_HEAD_REQUEST,
    payload: { url },
  }),

  getMinorHeadList: (url) => ({
    type: actions.MINOR_HEAD_REQUEST,
    payload: { url },
  }),

  getTeethList: (url) => ({
    type: actions.TEETH_REQUEST,
    payload: { url },
  }),

  getMustachesList: (url) => ({
    type: actions.MUSTACHES_REQUEST,
    payload: { url },
  }),

  getMolesList: (url) => ({
    type: actions.MOLES_REQUEST,
    payload: { url },
  }),

  getLanguagesList: (url) => ({
    type: actions.LANGUAGES_REQUEST,
    payload: { url },
  }),

  getDeformitiesList: (url) => ({
    type: actions.DEFORMITIES_REQUEST,
    payload: { url },
  }),

  getComplexionList: (url) => ({
    type: actions.COMPLEXION_REQUEST,
    payload: { url },
  }),

  getEyeColorList: (url) => ({
    type: actions.EYE_COLOR_REQUEST,
    payload: { url },
  }),

  getHairColorList: (url) => ({
    type: actions.HAIR_COLOR_REQUEST,
    payload: { url },
  }),

  getBeardList: (url) => ({
    type: actions.BEARD_REQUEST,
    payload: { url },
  }),

  getBodyTypeList: (url) => ({
    type: actions.BODY_TYPE_REQUEST,
    payload: { url },
  }),

  getRoadAccidentList: (url) => ({
    type: actions.ROAD_ACCIDENT_REQUEST,
    payload: { url },
  }),

  getActList: (url) => ({
    type: actions.ACT_REQUEST,
    payload: { url },
  }),

  getCisActList: (url) => ({
    type: actions.CIS_ACT_REQUEST,
    payload: { url },
  }),

  getSectionList: (url) => ({
    type: actions.SECTION_REQUEST,
    payload: { url },
  }),

  getDirectionFromPSList: (url) => ({
    type: actions.DIRECTION_FROM_PS_REQUEST,
    payload: { url },
  }),

  getMandalList: (url) => ({
    type: actions.MANDAL_REQUEST,
    payload: { url },
  }),

  getVillageFromPsList: (url) => ({
    type: actions.VILLAGE_FROM_PSCODE_REQUEST,
    payload: { url },
  }),

  getUnitsFromDistrict: (url) => ({
    type: actions.UNIT_FROM_DISTRICT_REQUEST,
    payload: { url },
  }),

  getCourtsBasedonPsCode: (url) => ({
    type: actions.COURTS_FROM_PSCODE_REQUEST,
    payload: { url },
  }),

  getFSLQuestionnairie: (url) => ({
    type: actions.FSL_QUESTIONNAIRIE_REQUEST,
    payload: { url },
  }),

  getIoDetails: (url) => ({
    type: actions.GET_IO_DETAILS_REQUEST,
    payload: { url },
  }),
};

export default actions;
