const actions = {
  FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST: "FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST",
  FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS: "FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS",
  FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR: "FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR",

  ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST: "ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST",
  ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS: "ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS",
  ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR: "ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR",

  UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST: "UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST",
  UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS: "UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_SUCCESS",
  UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR: "UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addProclamationAndPropertyAttachments: (url, body) => ({
    type: actions.ADD_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST,
    payload: { url, body },
  }),

  updateProclamationAndPropertyAttachments: (url, body) => ({
    type: actions.UPDATE_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST,
    payload: { url, body },
  }),

  getProclamationAndPropertyAttachmentsList: (url) => ({
    type: actions.FETCH_PROCLAMATION_AND_PROPERTY_ATTACHMENTS_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
