const actions = {
  FETCH_ACCUSED_DISPOSAL_FORM_REQUEST: "FETCH_ACCUSED_DISPOSAL_FORM_REQUEST",
  FETCH_ACCUSED_DISPOSAL_FORM_SUCCESS: "FETCH_ACCUSED_DISPOSAL_FORM_SUCCESS",
  FETCH_ACCUSED_DISPOSAL_FORM_ERROR: "FETCH_ACCUSED_DISPOSAL_FORM_ERROR",

  ADD_ACCUSED_DISPOSAL_FORM_REQUEST: "ADD_ACCUSED_DISPOSAL_FORM_REQUEST",
  ADD_ACCUSED_DISPOSAL_FORM_SUCCESS: "ADD_ACCUSED_DISPOSAL_FORM_SUCCESS",
  ADD_ACCUSED_DISPOSAL_FORM_ERROR: "ADD_ACCUSED_DISPOSAL_FORM_ERROR",

  UPDATE_ACCUSED_DISPOSAL_FORM_REQUEST: "UPDATE_ACCUSED_DISPOSAL_FORM_REQUEST",
  UPDATE_ACCUSED_DISPOSAL_FORM_SUCCESS: "UPDATE_ACCUSED_DISPOSAL_FORM_SUCCESS",
  UPDATE_ACCUSED_DISPOSAL_FORM_ERROR: "UPDATE_ACCUSED_DISPOSAL_FORM_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addAccusedDisposalForm: (url, body) => ({
    type: actions.ADD_ACCUSED_DISPOSAL_FORM_REQUEST,
    payload: { url, body },
  }),

  updateAccusedDisposalForm: (url, body) => ({
    type: actions.UPDATE_ACCUSED_DISPOSAL_FORM_REQUEST,
    payload: { url, body },
  }),

  getAccusedDisposalFormList: (url) => ({
    type: actions.FETCH_ACCUSED_DISPOSAL_FORM_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
