const actions = {
  FETCH_CRPC_164STATEMENT_REQUEST: "FETCH_CRPC_164STATEMENT_REQUEST",
  FETCH_CRPC_164STATEMENT_SUCCESS: "FETCH_CRPC_164STATEMENT_SUCCESS",
  FETCH_CRPC_164STATEMENT_ERROR: "FETCH_CRPC_164STATEMENT_ERROR",

  ADD_CRPC_164STATEMENT_REQUEST: "ADD_CRPC_164STATEMENT_REQUEST",
  ADD_CRPC_164STATEMENT_SUCCESS: "ADD_CRPC_164STATEMENT_SUCCESS",
  ADD_CRPC_164STATEMENT_ERROR: "ADD_CRPC_164STATEMENT_ERROR",

  UPDATE_CRPC_164STATEMENT_REQUEST: "UPDATE_CRPC_164STATEMENT_REQUEST",
  UPDATE_CRPC_164STATEMENT_SUCCESS: "UPDATE_CRPC_164STATEMENT_SUCCESS",
  UPDATE_CRPC_164STATEMENT_ERROR: "UPDATE_CRPC_164STATEMENT_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addCRPC164StatementDetails: (url, body) => ({
    type: actions.ADD_CRPC_164STATEMENT_REQUEST,
    payload: { url, body },
  }),

  updateCRPC164StatementDetails: (url, body) => ({
    type: actions.UPDATE_CRPC_164STATEMENT_REQUEST,
    payload: { url, body },
  }),

  getCRPC164StatementList: (url) => ({
    type: actions.FETCH_CRPC_164STATEMENT_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
