const actions = {
  FETCH_COURT_CASE_DIARY_REQUEST: "FETCH_COURT_CASE_DIARY_REQUEST",
  FETCH_COURT_CASE_DIARY_SUCCESS: "FETCH_COURT_CASE_DIARY_SUCCESS",
  FETCH_COURT_CASE_DIARY_ERROR: "FETCH_COURT_CASE_DIARY_ERROR",

  FETCH_CASE_DIARY_ID_REQUEST: "FETCH_CASE_DIARY_ID_REQUEST",
  FETCH_CASE_DIARY_ID_SUCCESS: "FETCH_CASE_DIARY_ID_SUCCESS",
  FETCH_CASE_DIARY_ID_ERROR: "FETCH_CASE_DIARY_ID_ERROR",

  ADD_COURT_CASE_DIARY_REQUEST: "ADD_COURT_CASE_DIARY_REQUEST",
  ADD_COURT_CASE_DIARY_SUCCESS: "ADD_COURT_CASE_DIARY_SUCCESS",
  ADD_COURT_CASE_DIARY_ERROR: "ADD_COURT_CASE_DIARY_ERROR",

  UPDATE_COURT_CASE_DIARY_REQUEST: "UPDATE_COURT_CASE_DIARY_REQUEST",
  UPDATE_COURT_CASE_DIARY_SUCCESS: "UPDATE_COURT_CASE_DIARY_SUCCESS",
  UPDATE_COURT_CASE_DIARY_ERROR: "UPDATE_COURT_CASE_DIARY_ERROR",

  RESET_COURT_CASE_DIARY_DATA: "RESET_COURT_CASE_DIARY_DATA",

  getCourtCaseDiary: (url) => ({
    type: actions.FETCH_COURT_CASE_DIARY_REQUEST,
    payload: { url },
  }),

  getCaseDiaryById: (url) => ({
    type: actions.FETCH_CASE_DIARY_ID_REQUEST,
    payload: { url },
  }),

  createCourtCaseDiary: (url, body) => ({
    type: actions.ADD_COURT_CASE_DIARY_REQUEST,
    payload: { url, body },
  }),

  updateCourtCaseDiary: (url, body) => ({
    type: actions.UPDATE_COURT_CASE_DIARY_REQUEST,
    payload: { url, body },
  }),

  resetCourtCaseDiaryAction: () => {
    return {
      type: actions.RESET_COURT_CASE_DIARY_DATA,
    };
  },
};

export default actions;
