const actions = {
  FETCH_REMAND_EXTENSION_REQUEST: "FETCH_REMAND_EXTENSION_REQUEST",
  FETCH_REMAND_EXTENSION_SUCCESS: "FETCH_REMAND_EXTENSION_SUCCESS",
  FETCH_REMAND_EXTENSION_ERROR: "FETCH_REMAND_EXTENSION_ERROR",

  ADD_REMAND_EXTENSION_REQUEST: "ADD_REMAND_EXTENSION_REQUEST",
  ADD_REMAND_EXTENSION_SUCCESS: "ADD_REMAND_EXTENSION_SUCCESS",
  ADD_REMAND_EXTENSION_ERROR: "ADD_REMAND_EXTENSION_ERROR",

  UPDATE_REMAND_EXTENSION_REQUEST: "UPDATE_REMAND_EXTENSION_REQUEST",
  UPDATE_REMAND_EXTENSION_SUCCESS: "UPDATE_REMAND_EXTENSION_SUCCESS",
  UPDATE_REMAND_EXTENSION_ERROR: "UPDATE_REMAND_EXTENSION_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addRemandExtensionDetails: (url, body) => ({
    type: actions.ADD_REMAND_EXTENSION_REQUEST,
    payload: { url, body },
  }),

  updateRemandExtensionDetails: (url, body) => ({
    type: actions.UPDATE_REMAND_EXTENSION_REQUEST,
    payload: { url, body },
  }),

  getRemandExtensionList: (url) => ({
    type: actions.FETCH_REMAND_EXTENSION_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
