const actions = {
  FETCH_BAIL_OPPOSITIONS_REQUEST: "FETCH_BAIL_OPPOSITIONS_REQUEST",
  FETCH_BAIL_OPPOSITIONS_SUCCESS: "FETCH_BAIL_OPPOSITIONS_SUCCESS",
  FETCH_BAIL_OPPOSITIONS_ERROR: "FETCH_BAIL_OPPOSITIONS_ERROR",

  ADD_BAIL_OPPOSITIONS_REQUEST: "ADD_BAIL_OPPOSITIONS_REQUEST",
  ADD_BAIL_OPPOSITIONS_SUCCESS: "ADD_BAIL_OPPOSITIONS_SUCCESS",
  ADD_BAIL_OPPOSITIONS_ERROR: "ADD_BAIL_OPPOSITIONS_ERROR",

  UPDATE_BAIL_OPPOSITIONS_REQUEST: "UPDATE_BAIL_OPPOSITIONS_REQUEST",
  UPDATE_BAIL_OPPOSITIONS_SUCCESS: "UPDATE_BAIL_OPPOSITIONS_SUCCESS",
  UPDATE_BAIL_OPPOSITIONS_ERROR: "UPDATE_BAIL_OPPOSITIONS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addBailOppositionsDetails: (url, body) => ({
    type: actions.ADD_BAIL_OPPOSITIONS_REQUEST,
    payload: { url, body },
  }),

  updateBailOppositionsDetails: (url, body) => ({
    type: actions.UPDATE_BAIL_OPPOSITIONS_REQUEST,
    payload: { url, body },
  }),

  getBailOppositionsList: (url) => ({
    type: actions.FETCH_BAIL_OPPOSITIONS_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
