const actions = {
  FETCH_JUVENILE_APPREHENSION_REQUEST: "FETCH_JUVENILE_APPREHENSION_REQUEST",
  FETCH_JUVENILE_APPREHENSION_SUCCESS: "FETCH_JUVENILE_APPREHENSION_SUCCESS",
  FETCH_JUVENILE_APPREHENSION_ERROR: "FETCH_JUVENILE_APPREHENSION_ERROR",

  ADD_JUVENILE_APPREHENSION_REQUEST: "ADD_JUVENILE_APPREHENSION_REQUEST",
  ADD_JUVENILE_APPREHENSION_SUCCESS: "ADD_JUVENILE_APPREHENSION_SUCCESS",
  ADD_JUVENILE_APPREHENSION_ERROR: "ADD_JUVENILE_APPREHENSION_ERROR",

  UPDATE_JUVENILE_APPREHENSION_REQUEST: "UPDATE_JUVENILE_APPREHENSION_REQUEST",
  UPDATE_JUVENILE_APPREHENSION_SUCCESS: "UPDATE_JUVENILE_APPREHENSION_SUCCESS",
  UPDATE_JUVENILE_APPREHENSION_ERROR: "UPDATE_JUVENILE_APPREHENSION_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addJuvenileApprehensionDetails: (url, body) => ({
    type: actions.ADD_JUVENILE_APPREHENSION_REQUEST,
    payload: { url, body },
  }),

  updateJuvenileApprehensionDetails: (url, body) => ({
    type: actions.UPDATE_JUVENILE_APPREHENSION_REQUEST,
    payload: { url, body },
  }),

  getJuvenileApprehensionList: (url) => ({
    type: actions.FETCH_JUVENILE_APPREHENSION_REQUEST,
    payload: { url },
  }),
  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
