import {
  TemplateRequisitionForInquest,
  TemplateSeizureReport,
} from "@containers/GenerateTemplates";
import {
  showPSName,
  getIONameAndRank,
  getTemplatesSectionsData,
} from "@containers/FirDetails/fir-util";
import { isEmpty } from "lodash";
import { loadState } from "@lib/helpers/localStorage";

export const StolenPropertyTemplates = [
  {
    name: "Notice U/Sec 50 NDPS Act",
    label: "Notice U/Sec 50 NDPS Act",
    fileName: "Notice_U/Sec_50_NDPS_Act",
    templateAvailable: true,
  },
  {
    name: "Seizure Report",
    label: "Seizure Report",
    fileName: "Seizure_Report",
    templateAvailable: true,
  },
];

export const SeizureReportTemplates = [
  {
    name: "Seizure Report",
    label: "Seizure Report",
    fileName: "Seizure_Report",
    templateAvailable: true,
  },
];

export const getHTMLFromTemplate = (filename, data) => {
  switch (filename) {
    case "Notice_U/Sec_50_NDPS_Act":
      return <TemplateRequisitionForInquest fileName={filename} data={data} />;
    case "Seizure_Report":
      return <TemplateSeizureReport fileName={filename} data={data} />;
    default:
      return "";
  }
};

export const getDataForDocument = (
  formData,
  fileName,
  selectedFir,
  firDetails,
  savedFir,
  editClicked,
  addressDetails,
  selectedStolenProperty
) => {
  const { firNum, district, psName, briefFacts } = selectedFir;
  const selectedActsData = loadState("selectedActDetails");
  var section =
    selectedFir?.actsAndSections &&
    selectedFir?.actsAndSections.map(function (i) {
      return i.section;
    });
  var merged = [].concat.apply([], section);
  var actsSections = merged?.toString();
  var secdata = !isEmpty(actsSections)
    ? getTemplatesSectionsData(selectedActsData?.uniqActs)
    : selectedFir?.section;
  const commonReportData = {
    policeStation: showPSName(psName),
    district: district,
    firNumber: firNum,
    sectionOfLaw: secdata,
    IOName: getIONameAndRank(briefFacts),
  };

  let reportData = {};
  switch (fileName) {
    case "Seizure_Report":
      const res = {
        dateOfSeizure: formData?.dateOfSeizure ? formData?.dateOfSeizure : "",
        firDate: selectedFir?.occurenceOfOffence?.firDate,
        firDetails: firDetails,
        savedFir: savedFir,
        editClicked: editClicked,
        addressDetails: addressDetails,
        selectedStolenProperty: selectedStolenProperty,
        formData: formData,
      };
      reportData = { ...commonReportData, ...res };
      break;
    default:
  }
  return reportData;
};

export const mainCategories = [
  {
    label: "Arms and Ammunition",
    value: "armsAndAmmunition",
  },
  {
    label: "Automobiles",
    value: "automobiles",
  },
  {
    label: "Coins and Currency",
    value: "coinsandCurrency",
  },
  {
    label: "Cultural Property",
    value: "culturalProperty",
  },
  {
    label: "Documents and Valuable Securities",
    value: "documentsandValuableSecurities",
  },
  {
    label: "Drugs/Narcotics",
    value: "drugsNarcotics",
  },
  {
    label: "Electrical and Electronic Goods",
    value: "electricalandElectronicGoods",
  },
  {
    label: "Explosives",
    value: "explosives",
  },
  {
    label: "Jewellery",
    value: "jewellery",
  },
  {
    label: "Miscellaneous",
    value: "miscellaneous",
  },
];

export const propertyStatus = [
  "Involved",
  "Lost",
  "Recovered",
  "Stolen",
  "Others",
];
export const propertyRecoveredFrom = [
  "Accused",
  "Abandoned",
  "Professional Receiver",
  "Others",
];
export const placeOfRecovery = ["Crime Scene", "Others"];
export const belongsToWhom = [
  "Abandoned",
  "Accused",
  "Complainant",
  "Government Property",
  "Private Property",
  "Unclaimed",
  "Victim",
  "Others (Specify)",
];

export const armsCategory = ["Bullets", "Guns", "Others"];
export const armsMake = ["Glock", "Sig Sauer"];
export const armsCountry = ["German", "Russia"];
export const armsBoreValues = ["12", "32"];
export const coinsDenomination = [
  "1",
  "2",
  "5",
  "10",
  "20",
  "50",
  "100",
  "200",
  "500",
  "1000",
  "2000",
];
export const culturalMaterial = ["Copper", "Silver", "Others"];
export const culturalNomenClature = ["Antique", "Others"];
export const drugsWeight = ["Gm", "Kg", "Lb", "Oz"];
export const drugsLocation = [
  "Farm House",
  "Guest House",
  "Open Place",
  "Private Area",
  "Private Parties",
  "Pubs",
  "Restaurants",
  "Under Ground",
  "Others",
];
export const explosiveChemicals = [
  "Azidoazide azide",
  "Black Powder",
  "Calcium Nitrate",
  "Sodium Chlorate",
  "Others",
];
export const natureOFStolen = [
  "Extortion",
  "Gem Stones",
  "Kandyan",
  "Pendent",
  "Robbery",
  "Theft",
  "Vessels",
  "Watches",
  "Others",
];
export const natureOFStolenArms = [
  "Explosive Auxiliaries",
  "Explosive Materials",
  "Explosives / Artillery Arms Ammunition",
  "Firearms Auxiliaries",
  "Heavy Artillery Arms",
  "Light Artillery Arms",
  "Sharp Arms",
  "Small Firearms (Factory Made)",
  "Small Firearms (Local Made)",
  "Small Firearms Ammunition",
  "Others",
];

export const natureOFStolenAuto = [
  "Aircraft",
  "Ambulance",
  "Animal Drawn Vehicle",
  "Articulated Vehicle",
  "Auto Electric",
  "Auto Rickshaw (Passenger)",
  "Auto Truck (Load Auto)",
  "Bicycle",
  "Car",
  "Car Electric / Golf Cart",
  "Cycle Rickshaw",
  "E-Bike",
  "Earth Mover",
  "Hand Drawn Vehicle",
  "Hand Rickshaw",
  "Harvester Tractor",
  "Heavy Truck",
  "Light Truck (Tempo)",
  "Lorry",
  "Mini Bus",
  "Mini Car",
  "Mini Truck",
  "Mini Van",
  "Miscellaneous",
  "Miscellaneous Mv Type",
  "Mobile Crane Lifter",
  "Mobile Loader/Excavator/ Bulldozer",
  "Mobile fork Lifter",
  "Moped",
  "Motor Boat",
  "Motor Cycle",
  "Private Bus",
  "Road Leveller/ Compactor / Carpeter",
  "Road Sweeper",
  "Ropeway (Gondola)",
  "Rtc Bus",
  "Rtv",
  "Scooter",
  "Scooterette",
  "Scooterette Electric",
  "Ship",
  "Small Truck / Lorry/ Multi Purpose Vehicle",
  "Small Van / Multi Purpose Van (Jeep)",
  "Station Wagon",
  "Tanker",
  "Taxi",
  "Tiller / Mini Tractor",
  "Tractor",
  "Trailer",
  "Trailer (Without Engine)",
  "Trailer Truck",
  "Train",
  "Van (Maxi) / Long Multi Purpose Van",
  "Others",
];

export const natureOFStolenCoins = [
  "Abu Dhabi/Dubai",
  "Afghanistan",
  "Africa",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Belorussia",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia - Herzegovina",
  "Botswana",
  "Brazil",
  "British Honduras",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costarica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Elsalvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Federation of Nigeria",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hongkong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland (Eire)",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhistan",
  "Kenya",
  "Kirgizia",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithunia",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaya",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Muscat",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Soloman Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "St Kitts - Nevis",
  "St Lucia",
  "St Vincent",
  "Sudan",
  "Surinam",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Tasmania",
  "Thailand",
  "Tibet",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkemanistan",
  "Turkey",
  "Tuvalli",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (Uae)",
  "United Kingdom (Uk)",
  "United States of America (Usa)",
  "Upper Valta",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Wallis &amp; Futuna Islands",
  "West Indies",
  "Western Australia",
  "Western Samoa",
  "Yeman",
  "Yugoslavia",
  "Yukon",
  "Zaire",
  "Zambia",
  "Zimbabwe",
  "Others",
];

export const natureOFStolenCultural = [
  "Antique Currency",
  "Apparel",
  "Artifacts",
  "Coins",
  "Idols",
  "Jewellery",
  "Maniature Paintaings",
  "Manuscript",
  "Monuments",
  "Ornaments",
  "Paintings",
  "Pictures",
  "Ritual/Pooja Articles",
  "Sculptures",
  "Tapestry",
  "Weapons",
  "Wood Work",
  "Others",
];

export const natureOFStolenDoucments = [
  "Account Books",
  "Affidavit",
  "Bank Drafts",
  "Bill Book",
  "Bill of Exchange",
  "Bills",
  "Bonds",
  "Cash Book",
  "Certificate",
  "Cheques",
  "Coupon",
  "Credit/Debit/ATM Card",
  "Debentures",
  "Earnest Money form",
  "Educational Certificate",
  "Engravings",
  "Files",
  "Fixed Deposit Receipt",
  "Govt Securities",
  "Govt Stamp Papers",
  "Hundies",
  "Identity Cards",
  "Indira Vikas Patra",
  "Inscriptions",
  "Invoice",
  "Kisan Vikas Patra",
  "Ledger Book",
  "Letter of Credit",
  "Licence",
  "Lottery Ticket",
  "Measurement Book (Mb S)",
  "Misc Documents",
  "Money Order",
  "Mortgage Deed",
  "Muster Roll Book",
  "National Savings Certificate",
  "Pass Book",
  "Passport",
  "Pay Book",
  "Permit",
  "Postal Order (Foreign)",
  "Postal Order (Indian)",
  "Power of Attorney",
  "Printing Blocks",
  "Promissory Note",
  "Ration Card",
  "Registration Certificate",
  "Sale Deed",
  "Securities",
  "Shares",
  "Stamp Papers",
  "Stamps",
  "Tender form",
  "Tickets",
  "Title Deed",
  "Traveller S Cheque",
  "Visa",
  "Voter ID Card",
  "Way Bill",
  "Will",
  "Others",
];

export const natureOFStolenDrugs = [
  "Amphetamine",
  "Barbiturate",
  "Bhang",
  "Brown Sugar",
  "Cannabis Plant",
  "Charas",
  "Coca Leaf",
  "Cocaine",
  "Codeine",
  "Crack",
  "Datura",
  "Ganja",
  "Hashish Oil",
  "Hasish",
  "Heroin (Diacetylmorphine)",
  "L.S.D (Lysergine)",
  "Lahan",
  "Liquor Bottle",
  "Mandrax",
  "Methaqualone",
  "Morphine",
  "Opium",
  "Opium Derivatives",
  "Plant Pod - Poppy",
  "Poppy Husk",
  "Poppy Plant Pod",
  "Poppy Straw",
  "Siddhi",
  "Smack",
  "Snow",
  "Toddy",
  "Wash",
  "Others",
];

export const natureOFStolenElectrical = [
  "Acsr Wire (Aluminium Core Steel Reinforced)",
  "Air Conditioner",
  "Air Cooler",
  "Aluminium Wires",
  "Amplifier",
  "Audio Cassette",
  "Audio Equipment",
  "Battery",
  "Bulb",
  "C.D. Player",
  "Cable",
  "Calculator",
  "Camera",
  "Cinema Projector",
  "Clock-Electric",
  "Compact Disc Player",
  "Computer",
  "Computer Accessories",
  "Cooking Range - Electric",
  "Copper Sheet",
  "Copper Wire",
  "Cordless Telephone",
  "CVT",
  "Dish Antenna",
  "Dish Washer",
  "Dynamos",
  "Electric Bell",
  "Electric Generator",
  "Electric Insect Repellent (Killer)",
  "Epabx System",
  "Exhaust Fan",
  "Fan",
  "Fax Machine",
  "Fire Detector",
  "Fire Extinguishers",
  "Fluorescent Lamp (Tube Light)",
  "Food Processor",
  "Generators",
  "Geyser",
  "Grinder",
  "Hair Drier",
  "Heater-Air",
  "Heater-Water",
  "Immersion Rod",
  "Integrated Circuits",
  "Intercom",
  "Iron Electric",
  "Kettle Electric",
  "Laptop",
  "Light Fittings",
  "Loudspeaker",
  "Mercury Vapour Lamp",
  "Meter Electric",
  "Microphones",
  "Microwave Oven",
  "Mixi",
  "Mobile Phone",
  "Modem",
  "Motor Electric",
  "Motor Pumps",
  "Movie Camera",
  "Music System (Incl. Stereo)",
  "Oven-Electric",
  "Over Head Projector",
  "Pager",
  "Pbx System",
  "Pedestal Lamp",
  "Photocopier",
  "Printer",
  "Radiogram",
  "Radios",
  "Receiver",
  "Record Player",
  "Records (Gramophone)",
  "Refrigerator",
  "Remote Control",
  "Sewing Machine-Electric",
  "Shaver-Electric",
  "Sim Cards",
  "Slide Projector",
  "Sodium Vapour Lamp",
  "Solar Light Fittings",
  "Starters",
  "Switches",
  "T.V. Accessories",
  "Table Lamp",
  "Tape Recorder",
  "Telephone",
  "Teleprinter",
  "Television",
  "Toaster-Electric",
  "Torch Light (Flash Light)",
  "Transformer",
  "Transistor",
  "Transmitter",
  "Two-In-One",
  "Uninterrupted Power Supply Equipment (UPS)",
  "Vcp",
  "Vcr",
  "Video Camera",
  "Video Cassette",
  "Voltage Stabilizer",
  "Washing Machine",
  "Water Cooler",
  "Welding Equipment",
  "Wireless Accessories",
  "Wireless Set",
  "Others",
];

export const natureOFStolenExplosives = [
  "A.N. / C.A.N.",
  "Acramite",
  "Anti Personnel Booby Traps",
  "Anti Personnel Mines",
  "Barium Nitrate",
  "Black Powder",
  "Bomb - Country Made",
  "Bomb - Crude form",
  "Bomb - H.E.",
  "Bomb - Remote Controlled",
  "Charcoal Chlorate",
  "Chinese Mixture-I",
  "Chlorate Mixture",
  "Cocktail Bomb",
  "Composition-B",
  "Composition-C 3",
  "Composition-C 4",
  "Cordite",
  "Cotton Explosives",
  "Detonator",
  "Dinitrobenzene",
  "Dinitrochlorobenzene",
  "Dinitroglycol",
  "Dinitrotoluene",
  "Dynamite (Tnt)",
  "Dynamite/Nitro Glycerine",
  "Explosive - D (Ammonium Picrate)",
  "Fireworks (Crackers)",
  "Fulminate",
  "Fuse",
  "Gelatine",
  "Grenade-Hand",
  "Gun Cotton",
  "Gun-Powder",
  "H.B.X.",
  "Improvised Explosive Device (Ied)",
  "Jelly",
  "K.D.N.B.F / Dinitrobenzo Furoxane",
  "L.M.N.R (Lead Mononstroresocinate)",
  "Land Mine",
  "Lead Azide",
  "Liquid Oxygen (LOX)",
  "Mercury Azide",
  "Mercury Fulminate",
  "Military Dynamite",
  "Molotov-Cocktails",
  "Nitrate Mixture",
  "Nitro Compound",
  "Nitro Glycerine",
  "Nitro-Starch",
  "P.E.T.N./Pettin",
  "Photo-Flash Powder",
  "Picric Acid",
  "Plastic Explosives",
  "Potassium Sulphate",
  "RDX",
  "Rocket",
  "Semtex",
  "Sheet Explosives",
  "Smokeless Powder",
  "Tacot",
  "Tetranitroaniline / Tna",
  "Tetranitrol / Erythrityltetra Nitrate",
  "Tetryl",
  "Trinitro Acetonenitrile",
  "Trinitro-N-Cresol / Cresolite",
  "Trinitroaniline (Picramide)",
  "Trinitroanisol (Methylpicr Ate)",
  "Trinitrobenzene (T.N.B.)",
  "Trinitrobenzoic Acid",
  "Trinitrochlorobenzene",
  "Trinitroglycerine",
  "Trinitromethylene Triamine / Cyclonite",
  "Trinitrophenol",
  "Trinitrophenyl Methylnitramine / Tetryl",
  "Trinitrophenyl Nitramine-Ethylnitrate",
  "Trinitroresorcinol / Styphnic Acid",
  "Trinitrotoluene / T.N.T.",
  "Trinitroxylene / Tnx",
  "Wax-Mix",
  "Others",
];

export const natureOFStolenJewellery = [
  "Diamond Bangles",
  "Diamond Necklace",
  "Diamond Ring",
  "Diamond Studs",
  "Gem Stones",
  "Gold Anklets",
  "Gold Armlet",
  "Gold Bangles",
  "Gold Biscuits",
  "Gold Bracelet",
  "Gold Coin",
  "Gold Ear Rings",
  "Gold Ear Stud",
  "Gold Finger Ring",
  "Gold Hair Pin",
  "Gold Head Cornet",
  "Gold Head Crown",
  "Gold Mangal Sutra",
  "Gold Neck Chain",
  "Gold Necklace",
  "Gold Nose Rings",
  "Gold Nose Screws",
  "Gold Shoulder Broach Pin",
  "Gold Waist Band",
  "Gold Waist Cord",
  "Ivory Articles",
  "Ivory Ornaments",
  "Kandyan",
  "Pendent",
  "Precious Material",
  "Precious Stone",
  "Silver Anklets",
  "Silver Block",
  "Silver Coin",
  "Silver Ear Rings",
  "Silver Ear Stud",
  "Silver Finger Rings",
  "Silver Head Cornet",
  "Silver Head Crown",
  "Silver Neck Chain",
  "Silver Necklace",
  "Silver Nose Rings",
  "Silver Nose Screws",
  "Silver Shoulder Broach Pin",
  "Silver Waist Band",
  "Silver Waist Cord",
  "Vessels",
  "Watches",
  "Others",
];

export const natureOFStolenMis = [
  "Alcoholic Beverages",
  "Beedi",
  "Books",
  "Cash",
  "Cigar",
  "Cigarette",
  "Display/ Cine Board",
  "Electricity",
  "Journals",
  "Leaflets",
  "Medicinal Preparation",
  "Metalware",
  "Pamphlets",
  "Periodicals",
  "Posters",
  "Publicity Materials",
  "Textile",
  "Tyre",
  "Water",
  "Yarn",
  "Others",
];
