const actions = {
  FETCH_COURT_DISPOSAL_FORM_REQUEST: "FETCH_COURT_DISPOSAL_FORM_REQUEST",
  FETCH_COURT_DISPOSAL_FORM_SUCCESS: "FETCH_COURT_DISPOSAL_FORM_SUCCESS",
  FETCH_COURT_DISPOSAL_FORM_ERROR: "FETCH_COURT_DISPOSAL_FORM_ERROR",

  ADD_COURT_DISPOSAL_FORM_REQUEST: "ADD_COURT_DISPOSAL_FORM_REQUEST",
  ADD_COURT_DISPOSAL_FORM_SUCCESS: "ADD_COURT_DISPOSAL_FORM_SUCCESS",
  ADD_COURT_DISPOSAL_FORM_ERROR: "ADD_COURT_DISPOSAL_FORM_ERROR",

  UPDATE_COURT_DISPOSAL_FORM_REQUEST: "UPDATE_COURT_DISPOSAL_FORM_REQUEST",
  UPDATE_COURT_DISPOSAL_FORM_SUCCESS: "UPDATE_COURT_DISPOSAL_FORM_SUCCESS",
  UPDATE_COURT_DISPOSAL_FORM_ERROR: "UPDATE_COURT_DISPOSAL_FORM_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",
  RESET_COURT_DISPOSAL_FORM_REQUEST: "RESET_COURT_DISPOSAL_FORM_REQUEST",
  addCourtDisposalForm: (url, body) => ({
    type: actions.ADD_COURT_DISPOSAL_FORM_REQUEST,
    payload: { url, body },
  }),

  updateCourtDisposalForm: (url, body) => ({
    type: actions.UPDATE_COURT_DISPOSAL_FORM_REQUEST,
    payload: { url, body },
  }),

  getCourtDisposalFormList: (url) => ({
    type: actions.FETCH_COURT_DISPOSAL_FORM_REQUEST,
    payload: { url },
  }),

  resetCourtDisposalFormList: () => {
    return {
      type: actions.RESET_COURT_DISPOSAL_FORM_REQUEST,
    };
  },

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
