const actions = {
  FETCH_APPEAL_ON_JUDGEMENT_REQUEST: "FETCH_APPEAL_ON_JUDGEMENT_REQUEST",
  FETCH_APPEAL_ON_JUDGEMENT_SUCCESS: "FETCH_APPEAL_ON_JUDGEMENT_SUCCESS",
  FETCH_APPEAL_ON_JUDGEMENT_ERROR: "FETCH_APPEAL_ON_JUDGEMENT_ERROR",

  ADD_APPEAL_ON_JUDGEMENT_REQUEST: "ADD_APPEAL_ON_JUDGEMENT_REQUEST",
  ADD_APPEAL_ON_JUDGEMENT_SUCCESS: "ADD_APPEAL_ON_JUDGEMENT_SUCCESS",
  ADD_APPEAL_ON_JUDGEMENT_ERROR: "ADD_APPEAL_ON_JUDGEMENT_ERROR",

  UPDATE_APPEAL_ON_JUDGEMENT_REQUEST: "UPDATE_APPEAL_ON_JUDGEMENT_REQUEST",
  UPDATE_APPEAL_ON_JUDGEMENT_SUCCESS: "UPDATE_APPEAL_ON_JUDGEMENT_SUCCESS",
  UPDATE_APPEAL_ON_JUDGEMENT_ERROR: "UPDATE_APPEAL_ON_JUDGEMENT_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addAppealOnJudgement: (url, body) => ({
    type: actions.ADD_APPEAL_ON_JUDGEMENT_REQUEST,
    payload: { url, body },
  }),

  updateAppealOnJudgement: (url, body) => ({
    type: actions.UPDATE_APPEAL_ON_JUDGEMENT_REQUEST,
    payload: { url, body },
  }),

  getAppealOnJudgementList: (url) => ({
    type: actions.FETCH_APPEAL_ON_JUDGEMENT_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
