export const investigationFormOptions1 = [
  {
    value: "preCrimeScene",
    label: "Pre Crime Scene",
    enabled: true,
    isDivider: false,
  },
  { value: "crimeScene", label: "Crime Scene", enabled: true, isDivider: true },
  {
    value: "planOfAction",
    label: "Plan of Action",
    enabled: false,
    isDivider: true,
  },
  {
    value: "MOSeizures",
    label: "MO Seizures",
    enabled: true,
    isDivider: false,
  },
  { value: "caseDiaryPart1", label: "Case Diary Part1", enabled: true },
  {
    value: "casePropertyManagement",
    label: "Case Property Management",
    enabled: true,
    isDivider: false,
  },
  {
    value: "stolenProperty",
    label: "Stolen Property",
    enabled: true,
    isDivider: true,
  },
  {
    value: "witnessStatement",
    label: "Witness Examination",
    enabled: true,
    isDivider: false,
  },
  {
    value: "crPcNotice160",
    label: "160 Cr.P.C Notice",
    enabled: true,
    isDivider: true,
  },
  { value: "inquest", label: "Inquest", enabled: true, isDivider: false },
  {
    value: "exhumation",
    label: "Exhumation",
    enabled: true,
    isDivider: false,
  },
  {
    value: "postmortemExamination",
    label: "Post-mortem Examination",
    enabled: true,
    isDivider: true,
  },
];

export const investigationFormOptions2 = [
  {
    value: "additionalMemo",
    label: "Additional Memo",
    enabled: true,
    isDivider: false,
  },
  {
    value: "alterationMemo",
    label: "Alteration Memo",
    enabled: true,
    isDivider: true,
  },
  {
    value: "collectionOfEvidence",
    label: "Collection Of Evidence",
    enabled: true,
    isDivider: false,
  },
  {
    value: "EffortsForTracing",
    label: "Efforts for Tracing",
    enabled: true,
    isDivider: false,
  },
  {
    value: "LookoutNotice",
    label: "Lookout Notice",
    enabled: true,
    isDivider: false,
  },
  {
    value: "form54",
    label: "Form 54",
    enabled: true,
    isDivider: true,
  },
  {
    value: "suspectAccused",
    label: "Accused Details",
    enabled: true,
    isDivider: false,
  },
  { value: "crPcNotice41A", label: "41A Cr.P.C Notice", enabled: true },
  {
    value: "arrest",
    label: "Arrest Related",
    displayArrestList: true,
    enabled: true,
    isDivider: false,
  },
  {
    value: "arrestByPolice",
    label: "Arrest By Police",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest By Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "arrestByOtherPolice",
    label: "Arrest by other Police",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest by other Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "arrestOnAnticipatoryBail",
    label: "Arrest on Anticipatory Bail",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest on Anticipatory Bail",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "arrestOnSurrenderInPoliceStation",
    label: "Arrest on Surrender in Police Station",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest on Surrender in Police Station",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "surrenderInCourt",
    label: "Surrender in Court",
    selectedActionFormData: "Surrender in Court",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "highCourtDirections",
    label: "High Court Directions",
    selectedActionFormData: "High Court Directions",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "surrenderBeforeCourt",
    label: "Surrender on Anticipatory Bail in Court",
    selectedActionFormData: "Surrender on Anticipatory Bail in Court",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "accusedOutOfCountry",
    label: "Accused Out of Country",
    selectedActionFormData: "Accused Out of Country",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
];

export const investigationFormOptions3 = [
  {
    value: "juvenileApprehension",
    label: "CCL Apprehension",
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionByPolice",
    label: "Apprehension By Police",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension By Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionByOtherPolice",
    label: "Apprehension by other Police",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension by other Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionOnAnticipatoryBail",
    label: "Apprehension on Anticipatory Bail",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension on Anticipatory Bail",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionOnSurrenderInPoliceStation",
    label: "Apprehension on Surrender in Police Station",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension on Surrender in Police Station",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "remandReport",
    label: "Remand Report",
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionReport",
    label: "Apprehension Report",
    enabled: true,
    isDivider: false,
  },
  {
    value: "confessionalStatements",
    label: "Confessional Statements",
    enabled: true,
    isDivider: false,
  },
  {
    value: "interrogationReport",
    label: "Interrogation Report",
    enabled: true,
    isDivider: false,
  },
  {
    value: "policeCustody",
    label: "Police Custody",
    enabled: true,
    isDivider: false,
  },
  {
    value: "remandExtension",
    label: "Remand Extension",
    enabled: true,
    isDivider: false,
  },
  {
    value: "PTWarrant",
    label: "Transit Warrant",
    enabled: true,
    isDivider: false,
  },
  {
    value: "bailOppositions",
    label: "Bail Oppositions",
    enabled: true,
    isDivider: true,
  },
  {
    value: "CRPCSec164StatementAccused",
    label: "Sec.164 Cr.P.C Statement of Accused",
    enabled: true,
    formType: "Accused",
    isDivider: false,
  },
  {
    value: "CRPCSec164StatementWitness",
    label: "Sec.164 Cr.P.C Statement of Witness",
    enabled: true,
    formType: "Witness",
    isDivider: false,
  },
  {
    value: "testIdentificationAccused",
    label: "Test Identification Of Accused",
    enabled: true,
    isDivider: false,
  },
  {
    value: "testIdentificationArticles",
    label: "Test Identification Of Articles",
    enabled: true,
    isDivider: true,
  },
];

export const investigationFormOptions4 = [
  {
    value: "prosecutionPermission",
    label: "Superior Officers Permission",
    enabled: true,
  },
  {
    value: "transferOfCaseFile",
    label: "Transfer of Case file",
    enabled: true,
    isDivider: false,
  },
  {
    value: "reassignmentOfCase",
    label: "Reassignment of Case",
    enabled: true,
    isDivider: true,
  },
  { value: "PPOpinion", label: "PP Opinion", enabled: true, isDivider: false },
  {
    value: "chargesheet",
    label: "Chargesheet",
    enabled: true,
    isDivider: false,
  },
  {
    value: "UpdateChargeSheetStatus",
    label: "Update Charge Sheet Status",
    enabled: true,
    isDivider: false,
  },
  {
    value: "finalReport",
    label: "Final Report",
    enabled: true,
    isDivider: false,
  },
  {
    value: "NoticeToComplainant",
    label: "Notice to Complainant",
    enabled: true,
    isDivider: true,
  },
  {
    value: "panchWitness",
    label: "Panch Witnesses",
    enabled: true,
    isDivider: false,
  },
  {
    value: "witnessDetails",
    label: "Witness Details",
    enabled: true,
    isDivider: false,
  },
];

export const investigationFormOptions = [
  { value: "preCrimeScene", label: "Pre Crime Scene", enabled: true },
  { value: "crimeScene", label: "Crime Scene", enabled: true },
  { value: "planOfAction", label: "Plan of Action", enabled: false },
  { value: "MOSeizures", label: "MO Seizures", enabled: true },
  { value: "caseDiaryPart1", label: "Case Diary Part1", enabled: true },
  {
    value: "casePropertyManagement",
    label: "Case Property Management",
    enabled: true,
  },
  { value: "stolenProperty", label: "Stolen Property", enabled: true },
  { value: "witnessStatement", label: "Witness Examination", enabled: true },
  {
    value: "crPcNotice160",
    label: "160 Cr.P.C Notice",
    enabled: true,
  },
  { value: "inquest", label: "Inquest", enabled: true },
  {
    value: "exhumation",
    label: "Exhumation",
    enabled: true,
  },
  {
    value: "postmortemExamination",
    label: "Post-mortem Examination",
    enabled: true,
  },
  { value: "additionalMemo", label: "Additional Memo", enabled: true },
  { value: "alterationMemo", label: "Alteration Memo", enabled: true },
  {
    value: "collectionOfEvidence",
    label: "Collection Of Evidence",
    enabled: true,
  },
  {
    value: "EffortsForTracing",
    label: "Efforts for Tracing",
    enabled: true,
  },
  { value: "LookoutNotice", label: "Lookout Notice", enabled: true },
  {
    value: "form54",
    label: "Form 54",
    enabled: true,
  },
  { value: "suspectAccused", label: "Accused Details", enabled: true },
  { value: "crPcNotice41A", label: "41A Cr.P.C Notice", enabled: true },
  {
    value: "arrest",
    label: "Arrest Related",
    displayArrestList: true,
    enabled: true,
  },
  {
    value: "arrestByPolice",
    label: "Arrest By Police",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest By Police",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "arrestByOtherPolice",
    label: "Arrest by other Police",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest by other Police",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "arrestOnAnticipatoryBail",
    label: "Arrest on Anticipatory Bail",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest on Anticipatory Bail",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "arrestOnSurrenderInPoliceStation",
    label: "Arrest on Surrender in Police Station",
    selectedActionFormData: "Arrest",
    selectedArrestFormData: "Arrest on Surrender in Police Station",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "surrenderInCourt",
    label: "Surrender in Court",
    selectedActionFormData: "Surrender in Court",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "highCourtDirections",
    label: "High Court Directions",
    selectedActionFormData: "High Court Directions",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "surrenderBeforeCourt",
    label: "Surrender on Anticipatory Bail in Court",
    selectedActionFormData: "Surrender on Anticipatory Bail in Court",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
  },
  {
    value: "accusedOutOfCountry",
    label: "Accused Out of Country",
    selectedActionFormData: "Accused Out of Country",
    selectedArrestFormData: "",
    displayArrestList: false,
    enabled: true,
  },

  {
    value: "juvenileApprehension",
    label: "CCL Apprehension",
    enabled: true,
  },
  {
    value: "apprehensionByPolice",
    label: "Apprehension By Police",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension By Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionByOtherPolice",
    label: "Apprehension by other Police",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension by other Police",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionOnAnticipatoryBail",
    label: "Apprehension on Anticipatory Bail",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension on Anticipatory Bail",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  {
    value: "apprehensionOnSurrenderInPoliceStation",
    label: "Apprehension on Surrender in Police Station",
    selectedActionFormData: "Apprehension",
    selectedArrestFormData: "Apprehension on Surrender in Police Station",
    displayArrestList: false,
    enabled: true,
    isDivider: false,
  },
  { value: "remandReport", label: "Remand Report", enabled: true },
  {
    value: "apprehensionReport",
    label: "Apprehension Report",
    enabled: true,
  },
  {
    value: "confessionalStatements",
    label: "Confessional Statements",
    enabled: true,
  },
  {
    value: "interrogationReport",
    label: "Interrogation Report",
    enabled: true,
  },
  {
    value: "policeCustody",
    label: "Police Custody",
    enabled: true,
  },
  { value: "remandExtension", label: "Remand Extension", enabled: true },
  {
    value: "PTWarrant",
    label: "Transit Warrant",
    enabled: true,
  },
  { value: "bailOppositions", label: "Bail Oppositions", enabled: true },
  {
    value: "CRPCSec164StatementAccused",
    label: "Sec.164 Cr.P.C Statement of Accused",
    enabled: true,
    formType: "Accused",
  },
  {
    value: "CRPCSec164StatementWitness",
    label: "Sec.164 Cr.P.C Statement of Witness",
    enabled: true,
    formType: "Witness",
  },
  {
    value: "testIdentificationAccused",
    label: "Test Identification Of Accused",
    enabled: true,
  },
  {
    value: "testIdentificationArticles",
    label: "Test Identification Of Articles",
    enabled: true,
  },
  {
    value: "prosecutionPermission",
    label: "Superior Officers Permission",
    enabled: true,
  },
  {
    value: "transferOfCaseFile",
    label: "Transfer of Case file",
    enabled: true,
  },
  {
    value: "reassignmentOfCase",
    label: "Reassignment of Case",
    enabled: true,
  },
  { value: "PPOpinion", label: "PP Opinion", enabled: true },
  { value: "chargesheet", label: "Chargesheet", enabled: true },
  {
    value: "UpdateChargeSheetStatus",
    label: "Update Charge Sheet Status",
    enabled: true,
  },
  { value: "finalReport", label: "Final Report", enabled: true },
  {
    value: "NoticeToComplainant",
    label: "Notice to Complainant",
    enabled: true,
  },
  { value: "panchWitness", label: "Panch Witnesses", enabled: true },
  { value: "witnessDetails", label: "Witness Details", enabled: true },
];

export const courtAndProsecutionMenu = [
  {
    value: "courtCommittal",
    label: "Court Committal",
    enabled: true,
  },
  {
    value: "issueOfSummons",
    label: "Issue Of Summons",
    enabled: true,
  },
  {
    value: "servingOfSummons",
    label: "Serving Of Summons",
    enabled: true,
  },
  {
    value: "courtTransfer",
    label: "Court Transfer",
    enabled: true,
  },
  {
    value: "courtCaseDiary",
    label: "Court Case Diary",
    enabled: true,
  },
  {
    value: "courtDisposalForm",
    label: "Court Disposal Form",
    enabled: true,
  },
  {
    value: "appealOnJudgement",
    label: "Appeal/Revision On Judgement",
    enabled: true,
  },
  {
    value: "issueOfWarrants",
    label: "Issue Of Warrants",
    enabled: true,
  },
  {
    value: "executingOfWarrants",
    label: "Executing Of Warrants",
    enabled: true,
  },
  {
    value: "noticeToSurety",
    label: "Notice to Surety",
    enabled: true,
  },
  {
    value: "proclamationAttachments",
    label: "Proclamation And Property Attachments",
    enabled: true,
  },
  {
    value: "deathOfAccused",
    label: "Death Of Accused",
    enabled: true,
  },
  {
    value: "accusedDisposalForm",
    label: "Accused Disposal Form",
    enabled: true,
  },
];

export const courtAndProsecutionLeftMenu = [
  {
    value: "courtCommittal",
    label: "Court Committal",
    enabled: true,
  },
  {
    value: "issueOfSummons",
    label: "Issue Of Summons",
    enabled: true,
  },
  {
    value: "servingOfSummons",
    label: "Serving Of Summons",
    enabled: true,
  },
  {
    value: "courtCaseDiary",
    label: "Court Case Diary",
    enabled: true,
  },
  {
    value: "issueOfWarrants",
    label: "Issue Of Warrants",
    enabled: true,
  },
  {
    value: "executingOfWarrants",
    label: "Executing Of Warrants",
    enabled: true,
  },
  {
    value: "noticeToSurety",
    label: "Notice to Surety",
    enabled: true,
  },
];

export const courtAndProsecutionRightMenu = [
  {
    value: "proclamationAttachments",
    label: "Proclamation And Property Attachments",
    enabled: true,
  },
  {
    value: "accusedDisposalForm",
    label: "Accused Disposal Form",
    enabled: true,
  },
  {
    value: "courtDisposalForm",
    label: "Court Disposal Form",
    enabled: true,
  },
  {
    value: "appealOnJudgement",
    label: "Appeal/Revision On Judgement",
    enabled: true,
  },
  {
    value: "deathOfAccused",
    label: "Death Of Accused",
    enabled: true,
  },
  {
    value: "courtTransfer",
    label: "Court Transfer",
    enabled: true,
  },
];

export const siderMenu = [
  { name: "Pre Crime Scene", value: "preCrimeScene" },
  { name: "Crime Scene", value: "crimeScene" },
  { name: "Plan of Action", value: "planOfAction" },
  { name: "Generate Requisitions", value: "generateRequisitions" },
  { name: "Investigation", value: "investigation" },
  { name: "Court And Prosecution", value: "courtandprosecution" },
  { name: "LOK Adalat Disposal", value: "lokAdalatDisposal" },
];

export const HIgherSHOsiderMenu = [
  { name: "Mini Investigation Report", value: "miniInvestigatinReport" },
  { name: "Advisory Memo", value: "advisoryMemo" },
  { name: "View FIR", value: "viewFir" },
  { name: "Court And Prosecution", value: "courtandprosecution" },
];
