const actions = {
  FETCH_EXECUTING_OF_WARRANTS_REQUEST: "FETCH_EXECUTING_OF_WARRANTS_REQUEST",
  FETCH_EXECUTING_OF_WARRANTS_SUCCESS: "FETCH_EXECUTING_OF_WARRANTS_SUCCESS",
  FETCH_EXECUTING_OF_WARRANTS_ERROR: "FETCH_EXECUTING_OF_WARRANTS_ERROR",

  ADD_EXECUTING_OF_WARRANTS_REQUEST: "ADD_EXECUTING_OF_WARRANTS_REQUEST",
  ADD_EXECUTING_OF_WARRANTS_SUCCESS: "ADD_EXECUTING_OF_WARRANTS_SUCCESS",
  ADD_EXECUTING_OF_WARRANTS_ERROR: "ADD_EXECUTING_OF_WARRANTS_ERROR",

  UPDATE_EXECUTING_OF_WARRANTS_REQUEST: "UPDATE_EXECUTING_OF_WARRANTS_REQUEST",
  UPDATE_EXECUTING_OF_WARRANTS_SUCCESS: "UPDATE_EXECUTING_OF_WARRANTS_SUCCESS",
  UPDATE_EXECUTING_OF_WARRANTS_ERROR: "UPDATE_EXECUTING_OF_WARRANTS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addExecutingOfWarrants: (url, body) => ({
    type: actions.ADD_EXECUTING_OF_WARRANTS_REQUEST,
    payload: { url, body },
  }),

  updateExecutingOfWarrants: (url, body) => ({
    type: actions.UPDATE_EXECUTING_OF_WARRANTS_REQUEST,
    payload: { url, body },
  }),

  getExecutingOfWarrantsList: (url) => ({
    type: actions.FETCH_EXECUTING_OF_WARRANTS_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
