const actions = {
  REPORTED_CHARGESHEET_REQUEST: "REPORTED_CHARGESHEET_REQUEST",
  REPORTED_CHARGESHEET_SUCCESS: "REPORTED_CHARGESHEET_SUCCESS",
  REPORTED_CHARGESHEET_ERROR: "REPORTED_CHARGESHEET_ERROR",

  CHARGESHEET_STATUS_REQUEST: "CHARGESHEET_STATUS_REQUEST",
  CHARGESHEET_STATUS_SUCCESS: "CHARGESHEET_STATUS_SUCCESS",
  CHARGESHEET_STATUS_ERROR: "CHARGESHEET_STATUS_ERROR",

  ICJS_REPORTS_DOWNLOAD_REQUEST: "ICJS_REPORTS_DOWNLOAD_REQUEST",
  ICJS_REPORTS_DOWNLOAD_SUCCESS: "ICJS_REPORTS_DOWNLOAD_SUCCESS",
  ICJS_REPORTS_DOWNLOAD_ERROR: "ICJS_REPORTS_DOWNLOAD_ERROR",

  PDF_REPORTS_DOWNLOAD_REQUEST: "PDF_REPORTS_DOWNLOAD_REQUEST",
  PDF_REPORTS_DOWNLOAD_SUCCESS: "PDF_REPORTS_DOWNLOAD_SUCCESS",
  PDF_REPORTS_DOWNLOAD_ERROR: "PDF_REPORTS_DOWNLOAD_ERROR",

  RESET_REPORT_REQUEST: "RESET_REPORT_REQUEST",

  fetchReportedChargeSheet: (url, body) => ({
    type: actions.REPORTED_CHARGESHEET_REQUEST,
    payload: { url, body },
  }),

  resetReportAction: () => ({
    type: actions.RESET_REPORT_REQUEST,
  }),

  fetchCasesChargeSheet: (url, body) => ({
    type: actions.CHARGESHEET_STATUS_REQUEST,
    payload: { url, body },
  }),

  downloadReports: (url, fileName) => ({
    type: actions.ICJS_REPORTS_DOWNLOAD_REQUEST,
    payload: { url, fileName },
  }),

  downloadPdfReports: (url) => ({
    type: actions.PDF_REPORTS_DOWNLOAD_REQUEST,
    payload: { url },
  }),
};

export default actions;
