const actions = {
  FETCH_FIR_MASTER_DATA_REQUEST: "FETCH_FIR_MASTER_DATA_REQUEST",
  FETCH_FIR_MASTER_DATA_SUCCESS: "FETCH_FIR_MASTER_DATA_SUCCESS",
  FETCH_FIR_MASTER_DATA_ERROR: "FETCH_FIR_MASTER_DATA_ERROR",

  FETCH_GENERATE_FIR_REQUEST: "FETCH_GENERATE_FIR_REQUEST",
  FETCH_GENERATE_FIR_SUCCESS: "FETCH_GENERATE_FIR_SUCCESS",
  FETCH_GENERATE_FIR_ERROR: "FETCH_GENERATE_FIR_ERROR",

  ADD_ACTS_SECTIONS_REQUEST: "ADD_ACTS_SECTIONS_REQUEST",
  ADD_ACTS_SECTIONS_SUCCESS: "ADD_ACTS_SECTIONS_SUCCESS",
  ADD_ACTS_SECTIONS_ERROR: "ADD_ACTS_SECTIONS_ERROR",

  ADD_OCCURRENCE_OF_OFFENCE_REQUEST: "ADD_OCCURRENCE_OF_OFFENCE_REQUEST",
  ADD_OCCURRENCE_OF_OFFENCE_SUCCESS: "ADD_OCCURRENCE_OF_OFFENCE_SUCCESS",
  ADD_OCCURRENCE_OF_OFFENCE_ERROR: "ADD_OCCURRENCE_OF_OFFENCE_ERROR",

  ADD_COMPLAINANT_REQUEST: "ADD_COMPLAINANT_REQUEST",
  ADD_COMPLAINANT_SUCCESS: "ADD_COMPLAINANT_SUCCESS",
  ADD_COMPLAINANT_ERROR: "ADD_COMPLAINANT_ERROR",

  ADD_BRIEF_FACTS_REQUEST: "ADD_BRIEF_FACTS_REQUEST",
  ADD_BRIEF_FACTS_SUCCESS: "ADD_BRIEF_FACTS_SUCCESS",
  ADD_BRIEF_FACTS_ERROR: "ADD_BRIEF_FACTS_ERROR",

  UPLOAD_DOCUMENTS_REQUEST: "UPLOAD_DOCUMENTS_REQUEST",
  UPLOAD_DOCUMENTS_SUCCESS: "UPLOAD_DOCUMENTS_SUCCESS",
  UPLOAD_DOCUMENTS_ERROR: "UPLOAD_DOCUMENTS_ERROR",

  DELETE_DOCUMENTS_REQUEST: "DELETE_DOCUMENTS_REQUEST",
  DELETE_DOCUMENTS_SUCCESS: "DELETE_DOCUMENTS_SUCCESS",
  DELETE_DOCUMENTS_ERROR: "DELETE_DOCUMENTS_ERROR",

  UPLOAD_FIR_REQUEST: "UPLOAD_FIR_REQUEST",
  UPLOAD_FIR_SUCCESS: "UPLOAD_FIR_SUCCESS",
  UPLOAD_FIR_ERROR: "UPLOAD_FIR_ERROR",

  ADD_PROPERTY_DETAILS_REQUEST: "ADD_PROPERTY_DETAILS_REQUEST",
  ADD_PROPERTY_DETAILS_SUCCESS: "ADD_PROPERTY_DETAILS_SUCCESS",
  ADD_PROPERTY_DETAILS_ERROR: "ADD_PROPERTY_DETAILS_ERROR",

  ADD_ACCUSED_DETAILS_REQUEST: "ADD_ACCUSED_DETAILS_REQUEST",
  ADD_ACCUSED_DETAILS_SUCCESS: "ADD_ACCUSED_DETAILS_SUCCESS",
  ADD_ACCUSED_DETAILS_ERROR: "ADD_ACCUSED_DETAILS_ERROR",

  ADD_VICTIM_DETAILS_REQUEST: "ADD_VICTIM_DETAILS_REQUEST",
  ADD_VICTIM_DETAILS_SUCCESS: "ADD_VICTIM_DETAILS_SUCCESS",
  ADD_VICTIM_DETAILS_ERROR: "ADD_VICTIM_DETAILS_ERROR",

  FETCH_GD_NUMBER_REQUEST: "FETCH_GD_NUMBER_REQUEST",
  FETCH_GD_NUMBER_SUCCESS: "FETCH_GD_NUMBER_SUCCESS",
  FETCH_GD_NUMBER_ERROR: "FETCH_GD_NUMBER_ERROR",

  FETCH_DEFAULT_MAJOR_HEAD_REQUEST: "FETCH_DEFAULT_MAJOR_HEAD_REQUEST",
  FETCH_DEFAULT_MAJOR_HEAD_SUCCESS: "FETCH_DEFAULT_MAJOR_HEAD_SUCCESS",
  FETCH_DEFAULT_MAJOR_HEAD_ERROR: "FETCH_DEFAULT_MAJOR_HEAD_ERROR",

  ADD_GENERATE_FIR_REQUEST: "ADD_GENERATE_FIR_REQUEST",
  ADD_GENERATE_FIR_SUCCESS: "ADD_GENERATE_FIR_SUCCESS",
  ADD_GENERATE_FIR_ERROR: "ADD_GENERATE_FIR_ERROR",

  UPDATE_FIR_REQUEST: "UPDATE_FIR_REQUEST",
  UPDATE_FIR_SUCCESS: "UPDATE_FIR_SUCCESS",
  UPDATE_FIR_ERROR: "UPDATE_FIR_ERROR",

  DELETE_FIR_REQUEST: "DELETE_FIR_REQUEST",
  DELETE_FIR_SUCCESS: "DELETE_FIR_SUCCESS",
  DELETE_FIR_ERROR: "DELETE_FIR_ERROR",

  COURTS_NAME_REQUEST: "COURTS_NAME_REQUEST",
  COURTS_NAME_SUCCESS: "COURTS_NAME_SUCCESS",
  COURTS_NAME_ERROR: "COURTS_NAME_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  RESET_UPDATE_ACTIONTYPE: "RESET_UPDATE_ACTIONTYPE",

  RESET_FIR_DATA: "RESET_FIR_DATA",

  createFIR: (url, body) => ({
    type: actions.ADD_GENERATE_FIR_REQUEST,
    payload: { url, body },
  }),

  updateFIR: (url, body) => ({
    type: actions.UPDATE_FIR_REQUEST,
    payload: { url, body },
  }),

  addActsSections: (url, body) => ({
    type: actions.ADD_ACTS_SECTIONS_REQUEST,
    payload: { url, body },
  }),

  addOccurrenceOfOffence: (url, body) => ({
    type: actions.ADD_OCCURRENCE_OF_OFFENCE_REQUEST,
    payload: { url, body },
  }),

  addComplainant: (url, body) => ({
    type: actions.ADD_COMPLAINANT_REQUEST,
    payload: { url, body },
  }),

  addBriefFacts: (url, body) => ({
    type: actions.ADD_BRIEF_FACTS_REQUEST,
    payload: { url, body },
  }),

  uploadDocumentDetails: (url, body) => ({
    type: actions.UPLOAD_DOCUMENTS_REQUEST,
    payload: { url, body },
  }),

  deleteDocumentDetails: (url, body) => ({
    type: actions.DELETE_DOCUMENTS_REQUEST,
    payload: { url, body },
  }),

  uploadFIR: (url, body) => ({
    type: actions.UPLOAD_FIR_REQUEST,
    payload: { url, body },
  }),

  addPropertyDetails: (url, body) => ({
    type: actions.ADD_PROPERTY_DETAILS_REQUEST,
    payload: { url, body },
  }),

  addAccusedDetails: (url, body) => ({
    type: actions.ADD_ACCUSED_DETAILS_REQUEST,
    payload: { url, body },
  }),

  addVictimDetails: (url, body) => ({
    type: actions.ADD_VICTIM_DETAILS_REQUEST,
    payload: { url, body },
  }),

  getFIRData: (url) => ({
    type: actions.FETCH_GENERATE_FIR_REQUEST,
    payload: { url },
  }),

  getDefaultMajorHead: (url, body) => ({
    type: actions.FETCH_DEFAULT_MAJOR_HEAD_REQUEST,
    payload: { url, body },
  }),

  deleteFIRData: (url, body) => ({
    type: actions.DELETE_FIR_REQUEST,
    payload: { url, body },
  }),

  getFirMasterData: (url, body) => ({
    type: actions.FETCH_FIR_MASTER_DATA_REQUEST,
    payload: { url, body },
  }),

  getGDNumbers: (url, body) => ({
    type: actions.FETCH_GD_NUMBER_REQUEST,
    payload: { url, body },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },

  resetFIRData: () => {
    return {
      type: actions.RESET_FIR_DATA,
    };
  },

  resetUpdateFir: () => {
    return {
      type: actions.RESET_UPDATE_ACTIONTYPE,
    };
  },
};

export default actions;
