const actions = {
  FETCH_LOK_ADALAT_DISPOSAL_REQUEST: "FETCH_LOK_ADALAT_DISPOSAL_REQUEST",
  FETCH_LOK_ADALAT_DISPOSAL_SUCCESS: "FETCH_LOK_ADALAT_DISPOSAL_SUCCESS",
  FETCH_LOK_ADALAT_DISPOSAL_ERROR: "FETCH_LOK_ADALAT_DISPOSAL_ERROR",

  ADD_LOK_ADALAT_DISPOSAL_REQUEST: "ADD_LOK_ADALAT_DISPOSAL_REQUEST",
  ADD_LOK_ADALAT_DISPOSAL_SUCCESS: "ADD_LOK_ADALAT_DISPOSAL_SUCCESS",
  ADD_LOK_ADALAT_DISPOSAL_ERROR: "ADD_LOK_ADALAT_DISPOSAL_ERROR",

  UPDATE_LOK_ADALAT_DISPOSAL_REQUEST: "UPDATE_LOK_ADALAT_DISPOSAL_REQUEST",
  UPDATE_LOK_ADALAT_DISPOSAL_SUCCESS: "UPDATE_LOK_ADALAT_DISPOSAL_SUCCESS",
  UPDATE_LOK_ADALAT_DISPOSAL_ERROR: "UPDATE_LOK_ADALAT_DISPOSAL_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addLokAdalatDisposal: (url, body) => ({
    type: actions.ADD_LOK_ADALAT_DISPOSAL_REQUEST,
    payload: { url, body },
  }),

  updateLokAdalatDisposal: (url, body) => ({
    type: actions.UPDATE_LOK_ADALAT_DISPOSAL_REQUEST,
    payload: { url, body },
  }),

  getLokAdalatDisposalList: (url) => ({
    type: actions.FETCH_LOK_ADALAT_DISPOSAL_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
