const actions = {
  FETCH_POSTMORTEM_EXAMINATION_REQUEST: "FETCH_POSTMORTEM_EXAMINATION_REQUEST",
  FETCH_POSTMORTEM_EXAMINATION_SUCCESS: "FETCH_POSTMORTEM_EXAMINATION_SUCCESS",
  FETCH_POSTMORTEM_EXAMINATION_ERROR: "FETCH_POSTMORTEM_EXAMINATION_ERROR",

  ADD_POSTMORTEM_EXAMINATION_REQUEST: "ADD_POSTMORTEM_EXAMINATION_REQUEST",
  ADD_POSTMORTEM_EXAMINATION_SUCCESS: "ADD_POSTMORTEM_EXAMINATION_SUCCESS",
  ADD_POSTMORTEM_EXAMINATION_ERROR: "ADD_POSTMORTEM_EXAMINATION_ERROR",

  UPDATE_POSTMORTEM_EXAMINATION_REQUEST: "UPDATE_POSTMORTEM_EXAMINATION_REQUEST",
  UPDATE_POSTMORTEM_EXAMINATION_SUCCESS: "UPDATE_POSTMORTEM_EXAMINATION_SUCCESS",
  UPDATE_POSTMORTEM_EXAMINATION_ERROR: "UPDATE_POSTMORTEM_EXAMINATION_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addPostmortemExaminationDetails: (url, body) => ({
    type: actions.ADD_POSTMORTEM_EXAMINATION_REQUEST,
    payload: { url, body },
  }),

  updatePostmortemExaminationDetails: (url, body) => ({
    type: actions.UPDATE_POSTMORTEM_EXAMINATION_REQUEST,
    payload: { url, body },
  }),

  getPostmortemExaminationList: (url) => ({
    type: actions.FETCH_POSTMORTEM_EXAMINATION_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
