const actions = {
  FETCH_REASSIGNMENT_OF_CASE_REQUEST: "FETCH_REASSIGNMENT_OF_CASE_REQUEST",
  FETCH_REASSIGNMENT_OF_CASE_SUCCESS: "FETCH_REASSIGNMENT_OF_CASE_SUCCESS",
  FETCH_REASSIGNMENT_OF_CASE_ERROR: "FETCH_REASSIGNMENT_OF_CASE_ERROR",

  ADD_REASSIGNMENT_OF_CASE_REQUEST: "ADD_REASSIGNMENT_OF_CASE_REQUEST",
  ADD_REASSIGNMENT_OF_CASE_SUCCESS: "ADD_REASSIGNMENT_OF_CASE_SUCCESS",
  ADD_REASSIGNMENT_OF_CASE_ERROR: "ADD_REASSIGNMENT_OF_CASE_ERROR",

  UPDATE_REASSIGNMENT_OF_CASE_REQUEST: "UPDATE_REASSIGNMENT_OF_CASE_REQUEST",
  UPDATE_REASSIGNMENT_OF_CASE_SUCCESS: "UPDATE_REASSIGNMENT_OF_CASE_SUCCESS",
  UPDATE_REASSIGNMENT_OF_CASE_ERROR: "UPDATE_REASSIGNMENT_OF_CASE_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addReassignmentOfCaseDetails: (url, body) => ({
    type: actions.ADD_REASSIGNMENT_OF_CASE_REQUEST,
    payload: { url, body },
  }),

  updateReassignmentOfCaseDetails: (url, body) => ({
    type: actions.UPDATE_REASSIGNMENT_OF_CASE_REQUEST,
    payload: { url, body },
  }),

  getReassignmentOfCaseList: (url) => ({
    type: actions.FETCH_REASSIGNMENT_OF_CASE_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
