export const reportTableConfig = [
  {
    type: "reportCases",
    typeName: "cases",
    data: [
      "S.No",
      "Cr.No & Sec.of Law, Crime Head,Gravity of Case",
      "Date of Occ.",
      "Place of Occ.",
      "Brief Facts",
      "Accused Name & Address",
      "Complainant Name & Address",
      "Prop.Lost(Rs.)",
      "Prop.Recd(Rs.)",
      "District",
      "PS Name"
    ],
  },
  {
    type: "summary",
    typeName: "Summary",
    data: ["S.No", "Crime Head", "No.Of Cases Reported", "Total"],
  },
  {
    type: "caseStatus",
    typeName: "Case Status",
    data: [
      "S.No",
      "No. of UI Cases",
      "No.of Cases Charged",
      "No. of PT Cases",
      "No. of Ref Cases",
      "No. of Court Disposals",
    ],
  },
  {
    type: "reasonForUI",
    typeName: "Reason for UI",
    data: [
      "S.No",
      "PME Pending",
      "PME Received",
      "MC Pending",
      "MC Received",
      "FSL Pending",
      "FSL Received",
      "CC Pending",
      "CC Received",
      "MVI Pending",
      "MVI Received",
      "Other Pending",
      "Other Received",
    ],
  },
  {
    type: "missingCases",
    typeName: "Missing Cases",
    data: [
      "S.No",
      "Cr.No & Sec.Of.Law",
      "Date of Occ.",
      "Place of Occ.",
      "Name of Complainant",
      "Name of Missing Person",
      "Age",
      "Brief Facts",
      "IO Name & Rank",
      "Missing Person Photo",
      "District",
      "PS Name"
    ],
  },
  {
    type: "UnknownDeadBodies",
    typeName: "Unknown Dead Bodies",
    data: [
      "S.No",
      "Cr.No & Sec.Of.Law",
      "Date of Occ.",
      "Place of Occ.",
      "Name of Complainant",
      "Unknown DeadBody Details",
      "Age",
      "Brief Facts",
      "IO Name & Rank",
      "Unknown DeadBody Photo",
      "District",
      "PS Name"
    ],
  },
  {
    type: "arrestWantedPersons",
    typeName: "Arrested Wanted Persons",
    data: [
      "S.No",
      "Crime Number",
      "Name and Address of the Persons Arrested",
      "Type",
      "Date of Arrest",
      "District",
      "PS Name"
    ],
  },
  {
    type: "crimeClassification",
    typeName: "Crime Classification",
    data: [
      "S.No",
      "Prop.Offn",
      "Bodily Offn",
      "White Collar Offn",
      "Crm.Against Women",
      "SC/ST POA",
      "Oth.IPC",
      "Total",
    ],
  },
  {
    type: "accidentInformationReport",
    typeName: "Accident Information Report",
    data: [
      "S.No",
      "FIR No",
      "FIR Date",
      "Acts and Sections",
      "Reference No",
      "Generated Date",
      "Tribunal Date",
      "Actions",
    ],
  },
];
