const actions = {
  FETCH_COMPLAINANT_DETAILS_REQUEST: "FETCH_COMPLAINANT_DETAILS_REQUEST",
  FETCH_COMPLAINANT_DETAILS_SUCCESS: "FETCH_COMPLAINANT_DETAILS_SUCCESS",
  FETCH_COMPLAINANT_DETAILS_ERROR: "FETCH_COMPLAINANT_DETAILS_ERROR",

  ADD_COMPLAINANT_DETAILS_REQUEST: "ADD_COMPLAINANT_DETAILS_REQUEST",
  ADD_COMPLAINANT_DETAILS_SUCCESS: "ADD_COMPLAINANT_DETAILS_SUCCESS",
  ADD_COMPLAINANT_DETAILS_ERROR: "ADD_COMPLAINANT_DETAILS_ERROR",

  UPDATE_COMPLAINANT_DETAILS_REQUEST: "UPDATE_COMPLAINANT_DETAILS_REQUEST",
  UPDATE_COMPLAINANT_DETAILS_SUCCESS: "UPDATE_COMPLAINANT_DETAILS_SUCCESS",
  UPDATE_COMPLAINANT_DETAILS_ERROR: "UPDATE_COMPLAINANT_DETAILS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addComplainantDetailsDetails: (url, body) => ({
    type: actions.ADD_COMPLAINANT_DETAILS_REQUEST,
    payload: { url, body },
  }),

  updateComplainantDetailsDetails: (url, body) => ({
    type: actions.UPDATE_COMPLAINANT_DETAILS_REQUEST,
    payload: { url, body },
  }),

  getComplainantDetailsList: (url) => ({
    type: actions.FETCH_COMPLAINANT_DETAILS_REQUEST,
    payload: { url },
  }),

  resetComplainantActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
