const actions = {
  FETCH_STOLEN_PROPERTY_REQUEST: "FETCH_STOLEN_PROPERTY_REQUEST",
  FETCH_STOLEN_PROPERTY_SUCCESS: "FETCH_STOLEN_PROPERTY_SUCCESS",
  FETCH_STOLEN_PROPERTY_ERROR: "FETCH_STOLEN_PROPERTY_ERROR",

  ADD_STOLEN_PROPERTY_REQUEST: "ADD_STOLEN_PROPERTY_REQUEST",
  ADD_STOLEN_PROPERTY_SUCCESS: "ADD_STOLEN_PROPERTY_SUCCESS",
  ADD_STOLEN_PROPERTY_ERROR: "ADD_STOLEN_PROPERTY_ERROR",

  DELETE_STOLEN_PROPERTY_REQUEST: "DELETE_STOLEN_PROPERTY_REQUEST",
  DELETE_STOLEN_PROPERTY_SUCCESS: "DELETE_STOLEN_PROPERTY_SUCCESS",
  DELETE_STOLEN_PROPERTY_ERROR: "DELETE_STOLEN_PROPERTY_ERROR",

  UPDATE_STOLEN_PROPERTY_REQUEST: "UPDATE_STOLEN_PROPERTY_REQUEST",
  UPDATE_STOLEN_PROPERTY_SUCCESS: "UPDATE_STOLEN_PROPERTY_SUCCESS",
  UPDATE_STOLEN_PROPERTY_ERROR: "UPDATE_STOLEN_PROPERTY_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addStolenPropertyDetails: (url, body) => ({
    type: actions.ADD_STOLEN_PROPERTY_REQUEST,
    payload: { url, body },
  }),

  deleteStolenPropertyDetails: (url, body) => ({
    type: actions.DELETE_STOLEN_PROPERTY_REQUEST,
    payload: { url, body },
  }),


  updateStolenPropertyDetails: (url, body) => ({
    type: actions.UPDATE_STOLEN_PROPERTY_REQUEST,
    payload: { url, body },
  }),

  getStolenPropertyList: (url) => ({
    type: actions.FETCH_STOLEN_PROPERTY_REQUEST,
    payload: { url },
  }),
  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
