const actions = {
  FETCH_DASHBOARD_TRANSFER_OF_CASE_REQUEST:
    "FETCH_DASHBOARD_TRANSFER_OF_CASE_REQUEST",
  FETCH_DASHBOARD_TRANSFER_OF_CASE_SUCCESS:
    "FETCH_DASHBOARD_TRANSFER_OF_CASE_SUCCESS",
  FETCH_DASHBOARD_TRANSFER_OF_CASE_ERROR:
    "FETCH_DASHBOARD_TRANSFER_OF_CASE_ERROR",

  DASHBOARD_TRANSFER_OF_CASE_POST_REQUEST:
    "DASHBOARD_TRANSFER_OF_CASE_POST_REQUEST",
  DASHBOARD_TRANSFER_OF_CASE_POST_SUCCESS:
    "DASHBOARD_TRANSFER_OF_CASE_POST_SUCCESS",
  DASHBOARD_TRANSFER_OF_CASE_POST_ERROR:
    "DASHBOARD_TRANSFER_OF_CASE_POST_ERROR",

  fetchDashboardTransferOfCase: (url, body) => ({
    type: actions.FETCH_DASHBOARD_TRANSFER_OF_CASE_REQUEST,
    payload: { url, body },
  }),

  postDashboardTransferOfCase: (url, body) => ({
    type: actions.DASHBOARD_TRANSFER_OF_CASE_POST_REQUEST,
    payload: { url, body },
  }),
};

export default actions;
