export const API_GATEWAY_URL = process.env.REACT_APP_GATEWAY_URL;
export const API_Environment = process.env.REACT_APP_API_Environment;
export const REPORT_LOGO_FILE_ID =
  process.env.REACT_APP_MM_TEMPLATE_LOGO_FILE_ID;

export const API_BASE_URL = API_GATEWAY_URL
  ? API_GATEWAY_URL + (API_Environment === "PROD" ? "/api/baseapi" : "/api")
  : // : "http://10.20.2.166:18080"; // ecops DEV url
    "http://10.121.9.139:18080"; // ecops DEV2 url
// : "http://10.121.9.139:18081";  // ecops QA2 url
// : "http://10.20.2.166:18080"; // ecops uat url

export const API_ARREST_BASE_URL = API_GATEWAY_URL
  ? API_GATEWAY_URL + (API_Environment === "PROD" ? "/api/arrest" : "/arrest")
  : "http://10.121.9.139:48080";
//http://10.121.9.68:48080 ecops dev
//http://10.121.9.139:48081/- ecopsqa2
//http://10.121.9.139:48080/-ecops dev2
//API_ARREST_BASE_URL
export const API_FILE_UPLOAD_BASE_URL = API_GATEWAY_URL
  ? API_GATEWAY_URL +
    (API_Environment === "PROD" ? "/api/media-manager" : "/media-manager")
  : "http://10.121.9.139:58080";
//http://10.121.9.68:58080 ecops dev
//http://10.121.9.139:58081-qa2
//http://10.121.9.139:58080-dev2
//API_FILE_UPLOAD_BASE_URL

export const API_CIS_BASE_URL = API_GATEWAY_URL
  ? API_GATEWAY_URL + (API_Environment === "PROD" ? "/api/cis" : "/cis")
  : "http://10.121.9.139:19100";
// http://10.121.9.68:19100 ecops dev
// http://10.121.9.139:19101-qa2
// http://10.121.9.139:19100-dev2
// API_CIS_BASE_URL
export const API_KEY = process.env.REACT_APP_API_KEY;

export const API_TABLEAU_BASE_URL = "http://10.20.2.218";

export const config = {
  login: API_GATEWAY_URL
    ? API_Environment === "PROD"
      ? `${API_GATEWAY_URL}/api/login/login`
      : `${API_GATEWAY_URL}/login`
    : `${API_BASE_URL}/login`,
  getTsHierarchyList: `${API_CIS_BASE_URL}/cis/reports/getTsHierarchy`,
  getUnknownMissingPDFs: `${API_CIS_BASE_URL}/cis/reports/getUnknownMissingData`,
  cisActsAndSection: `${API_CIS_BASE_URL}/cis/reports/getActs`,
  getRecentEditList: `${API_BASE_URL}/api/dashboard/getRecentEditList`,
  getCaseMetricsByEMail: `${API_BASE_URL}/api/dashboard/getCaseMetricsByEMail`,
  getRecentFirList: `${API_BASE_URL}/api/dashboard/getRecentFirList`,
  getRecentFirListMobile: `${API_BASE_URL}/api/dashboard/getRecentFirListMobile`,
  getAdvisoryFIRList: `${API_BASE_URL}/api/dashboard/getAdvisoryFIRList`,
  approvalAction: `${API_BASE_URL}/api/workflow/action`,
  reRegistrationFir: `${API_BASE_URL}/api/transfer-of-case-file/re-register-crime`,
  upsertCrimeAdvisory: `${API_BASE_URL}/api/m_new/upsertCrimeAdvisory`,
  getTransferredZeroFIRHistory: `${API_BASE_URL}/api/dashboard/getTransferredZeroFIRHistory`,
  getReceivedZeroFIRHistory: `${API_BASE_URL}/api/dashboard/getReceivedZeroFIRHistory`,
  getCasesCountByYear: `${API_BASE_URL}/api/dashboard/getCasesCountByYear`,
  getApprovalFIRList: `${API_BASE_URL}/api/dashboard/getApprovalFIRList`,
  getPreCrimeData: `${API_BASE_URL}/api/case/getPreCrimeData`,
  getExpertTeamFromHrms: `${API_BASE_URL}/api/hrms/getExpertTeamFromHrms`,
  getSupportStaffFromHrms: `${API_BASE_URL}/api/hrms/getSupportStaffFromHrms`,
  getAllSupportStaffFromHrms: `${API_BASE_URL}/api/hrms/getAllSupportStaffFromHrms`,
  updatePreCrimeCase: `${API_BASE_URL}/api/case/updatePreCrimeCase`,
  historyOptions: `${API_BASE_URL}/api/case/historyOptions`,
  caseProperty: `${API_BASE_URL}/api/caseProperty`,
  addAckFSL: `${API_BASE_URL}/api/caseProperty/addAckFSL`,
  actionAckFSL: `${API_BASE_URL}/api/caseProperty/actionAckFSL`,
  getFSLCasesInfo: `${API_BASE_URL}/api/caseProperty/getFSLCasesInfo`,
  getPostCrimeSceneDetails: `${API_BASE_URL}/api/case/getPostCrimeSceneDetails`,
  updateCrimeClassification: `${API_BASE_URL}/api/case/updateCrimeClassification`,
  addMaterialObject: `${API_BASE_URL}/api/case/addMaterialObject`,
  updateMaterialObject: `${API_BASE_URL}/api/case/updateMaterialObject`,
  addExpertTeamDetails: `${API_BASE_URL}/api/case/addExpertTeamDetails`,
  updateExpertTeamDetails: `${API_BASE_URL}/api/case/updateExpertTeamDetails`,
  addWitnessDetails: `${API_BASE_URL}/api/case/addWitnessDetails`,
  updateWitnessDetail: `${API_BASE_URL}/api/case/updateWitnessDetail`,
  updateWitnessOrder: `${API_BASE_URL}/api/case/updateWitnessOrder`,
  addPanchWitness: `${API_BASE_URL}/api/case/addPanchWitness`,
  updatePanchWitness: `${API_BASE_URL}/api/case/updatePanchWitness`,
  addDeceasedDetails: `${API_BASE_URL}/api/case/addDeceasedDetails`,
  crimeLocation: `${API_BASE_URL}/api/case/crimeLocation`,
  updateCrimeLocation: `${API_BASE_URL}/api/case/updateCrimeLocation`,
  getWitnessStatements: `${API_BASE_URL}/api/case/getWitnessStatements`,
  updateWitnessStatement: `${API_BASE_URL}/api/case/updateWitnessStatement`,
  updatePersonMediaDetails: `${API_BASE_URL}/api/case/updatePersonMediaDetails`,
  addWitnessStatement: `${API_BASE_URL}/api/case/addWitnessStatement`,
  addUpdateCrimeClassification: `${API_BASE_URL}/api/case/addUpdateCrimeClassification`,
  roughSketch: `${API_BASE_URL}/api/case/roughSketch`,
  addAccusedDetails: `${API_BASE_URL}/api/case/addAccusedDetails`,
  updateAccusedDetails: `${API_BASE_URL}/api/case/updateAccusedDetails`,
  addNotice160Details: `${API_BASE_URL}/api/case/addNotice160Details`,
  tableauReportData: `${API_BASE_URL}/api/reoprts/tableau-report`,
  getAccusedList: `${API_BASE_URL}/api/case/getAccusedList`,
  getPPOpinion: `${API_BASE_URL}/api/case/getPPOpinion`,
  getMoSeizedForChargeSheet: `${API_BASE_URL}/api/case/getMoSeizedForChargeSheet`,
  addPPOpinion: `${API_BASE_URL}/api/case/addPPOpinion`,
  addUpdateEffortsTracing: `${API_BASE_URL}/api/case/addUpdateEffortsTracing`,
  updatePPOpinion: `${API_BASE_URL}/api/case/updatePPOpinion`,
  getComplainantNotice: `${API_BASE_URL}/api/case/getComplainantNotice`,
  addComplainantNotice: `${API_BASE_URL}/api/case/addComplainantNotice`,
  updateComplainantNotice: `${API_BASE_URL}/api/case/updateComplainantNotice`,
  addComplainantDetails: `${API_BASE_URL}/api/case/addComplainantDetails`,
  updateComplainantDetails: `${API_BASE_URL}/api/case/updateComplainantDetails`,
  masterData: `${API_BASE_URL}/api/masterdata`,
  getMasterData: `${API_BASE_URL}/api/masterdata/getMasterData`,
  getUnitMapping: `${API_BASE_URL}/api/masterdata/getUnitMapping`,
  getTsHierarchy: `${API_BASE_URL}/api/masterdata/getTsHierarchy`,
  getReassignmentHierarchy: `${API_BASE_URL}/api/masterdata/getReassignmentHierarchy`,
  getMandalVillage: `${API_BASE_URL}/api/masterdata/getMandalVillage`,
  getDistrictVillage: `${API_BASE_URL}/api/masterdata/getDistrictVillage`,
  getMasterDataMultiple: `${API_BASE_URL}/api/masterdata/getMasterDataMultiple`,
  getQuestionnairie: `${API_BASE_URL}/api/masterdata/getQuestionnairie`,
  getVehicleInfo: `${API_BASE_URL}/api/masterdata/getVehicleInfo`,
  getStateDistrict: `${API_BASE_URL}/api/masterdata/getStateDistrict`,
  interrogation: `${API_BASE_URL}/api/interrogation`,
  fileUpload: `${API_FILE_UPLOAD_BASE_URL}/api/file`,
  getFile: `${API_FILE_UPLOAD_BASE_URL}/api/file/thumbnail`,
  downloadFile: `${API_FILE_UPLOAD_BASE_URL}/api/file/download`,
  resizedImageDownload: `${API_FILE_UPLOAD_BASE_URL}/api/file/resizedImageDownload`,
  getChargeSheet: `${API_BASE_URL}/api/case/getChargeSheet`,
  addUpdateChargeSheet: `${API_BASE_URL}/api/case/addUpdateChargeSheet`,
  addUpdateChangeChargeSheetStatus: `${API_BASE_URL}/api/case/addUpdateChangeChargeSheetStatus`,
  addUpdateChangeChargeSheetStatusv2: `${API_BASE_URL}/api/case/addUpdateChangeChargeSheetStatusv2`,
  getUpdateChargeSheetStatus: `${API_BASE_URL}/api/case/getUpdateChargeSheetStatus`,
  getUpdateChargeSheetStatusv2: `${API_BASE_URL}/api/case/getUpdateChargeSheetStatusv2`,
  uploadChargeSheetReport: `${API_BASE_URL}/api/case/uploadChargeSheetReport`,
  courtCommittal: `${API_BASE_URL}/api/courts-prosecutions/court-committal`,
  courtSummons: `${API_BASE_URL}/api/courts-prosecutions/court-summons`,
  IssueOfSummons: `${API_BASE_URL}/api/courts-prosecutions/court-summons`,
  accusedDisposalForm: `${API_BASE_URL}/api/courts-prosecutions/accused-disposal`,
  courtTransfer: `${API_BASE_URL}/api/courts-prosecutions/court-transfer-details`,
  appealOnJudgement: `${API_BASE_URL}/api/courts-prosecutions/appeal_on_judgement`,
  createDeathOfAccused: `${API_BASE_URL}/api/courts-prosecutions/createDeathOfAccused`,
  updateDeathOfAccused: `${API_BASE_URL}/api/courts-prosecutions/updateDeathOfAccused`,
  getDeathOfAccused: `${API_BASE_URL}/api/courts-prosecutions/getDeathOfAccused`,
  accusedDisposal: `${API_BASE_URL}/api/courts-prosecutions/accused-disposal`,
  CourtDisposal: `${API_BASE_URL}/api/courts-prosecutions/court-disposal-form`,
  courtCaseDiary: `${API_BASE_URL}/api/courts-prosecutions/court-case-diary`,
  defenseWitnessExamination: `${API_BASE_URL}/api/courts-prosecutions/court-case-diary/defense-witness-examination`,
  appearanCourtCaseDiary: `${API_BASE_URL}/api/courts-prosecutions/court-case-diary`,
  IssueOfWarrants: `${API_BASE_URL}/api/courts-prosecutions/issue-of-warrant`,
  NoticetoSurity: `${API_BASE_URL}/api/courts-prosecutions`,
  appearanceAccusedCaseDiary: `${API_BASE_URL}/api/courts-prosecutions/court-case-diary/appearance-accused`,
  publishingProclamation: `${API_BASE_URL}/api/courts-prosecutions/publishing-proclamation`,
  propertyAttachments: `${API_BASE_URL}/api/courts-prosecutions/property-attachments`,
  createProclamation: `${API_BASE_URL}/api/courts-prosecutions/proclamation-publishing-property`,
  updateProclamation: `${API_BASE_URL}/api/courts-prosecutions/proclamation-publishing-property`,
  getProclamation: `${API_BASE_URL}/api/courts-prosecutions/proclamation-publishing-property`,
  lokAdalatDisposal: `${API_BASE_URL}/api/courts-prosecutions/Lok-Adalat-Disposal`,
  uploadCrimeScene: `${API_BASE_URL}/api/case/uploadCrimeLocation`,
  noticetosurety: `${API_BASE_URL}/api/interrogation/get-sureties`,
  getFinalReport: `${API_BASE_URL}/api/case/getFinalReport`,
  addUpdateFinalReport: `${API_BASE_URL}/api/case/addUpdateFinalReport`,
  uploadFinalReport: `${API_BASE_URL}/api/case/uploadFinalReport`,
  addScientificEvidence: `${API_BASE_URL}/api/case/addScientificEvidence`,
  updateScientificEvidence: `${API_BASE_URL}/api/case/updateScientificEvidence`,
  addUpdateDocumentaryEvidence: `${API_BASE_URL}/api/case/addUpdateDocumentaryEvidence`,
  getEvidenceDetails: `${API_BASE_URL}/api/case/getEvidenceDetails`,
  addDOC: `${API_BASE_URL}/api/case/addDOC`,
  updateDOC: `${API_BASE_URL}/api/case/updateDOC`,
  addCCTVFootage: `${API_BASE_URL}/api/case/addCCTVFootage`,
  updateCCTVFootage: `${API_BASE_URL}/api/case/updateCCTVFootage`,
  addAudioVideo: `${API_BASE_URL}/api/case/addAudioVideo`,
  updateAudioVideo: `${API_BASE_URL}/api/case/updateAudioVideo`,
  addCDR: `${API_BASE_URL}/api/case/addCDR`,
  updateCDR: `${API_BASE_URL}/api/case/updateCDR`,
  generateNewFIR: `${API_BASE_URL}/api/fir/generateNewFIR`,
  updateFIR: `${API_BASE_URL}/api/fir/updateFIR`,
  getRecentFirNum: `${API_BASE_URL}/api/fir/getRecentFirNum`,
  deleteFIR: `${API_BASE_URL}/api/fir/deleteFIR`,
  deletePersonDetails: `${API_BASE_URL}/api/fir/deletePersonDetails`,
  deleteStolenProperty: `${API_BASE_URL}/api/fir/deleteStolenProperty`,
  getFIR: `${API_BASE_URL}/api/fir/getFIR`,
  getInitialFIR: `${API_BASE_URL}/api/fir/getInitialFIR`,
  uploadFirReport: `${API_BASE_URL}/api/fir/uploadFirReport`,
  getGDNumbers: `${API_BASE_URL}/api/fir/getGDNumbers`,
  getDefaultMajorHead: `${API_BASE_URL}/api/fir/getDefaultMajorHead`,
  getCrimeScenePhotos: `${API_BASE_URL}/api/case/getCrimeScenePhotos`,
  updateCrimeScenePhotos: `${API_BASE_URL}/api/case/updateCrimeScenePhotos`,
  getAlterationMemo: `${API_BASE_URL}/api/case/getAlterationMemo`,
  addAlterationMemo: `${API_BASE_URL}/api/case/addAlterationMemo`,
  updateAlterationMemo: `${API_BASE_URL}/api/case/updateAlterationMemo`,
  createCaseDiary: `${API_BASE_URL}/api/case/createCaseDiary`,
  updateCaseDiary: `${API_BASE_URL}/api/case/updateCaseDiary`,
  getCaseDiary: `${API_BASE_URL}/api/case/getCaseDiary`,
  deleteCaseDiary: `${API_BASE_URL}/api/case/deleteCaseDiary`,
  createAudits: `${API_BASE_URL}/api/audit/createAudits`,
  getDashboardTransferOfCase: `${API_BASE_URL}/api/dashboard/getTransferOfCase`,
  getMiniInvestigation: `${API_BASE_URL}/api/fir/getFIRMobile`,
  arrest: `${API_ARREST_BASE_URL}/api/arrest`,
  policeCustody: `${API_ARREST_BASE_URL}/api/policeCustody`,
  ptWarrant: `${API_ARREST_BASE_URL}/api/ptWarrant`,
  tipAccused: `${API_ARREST_BASE_URL}/api/tipAccused`,
  tipArticles: `${API_ARREST_BASE_URL}/api/tipArticle`,
  stolenProperty: `${API_ARREST_BASE_URL}/api/stolenProperty`,
  remandReport: `${API_ARREST_BASE_URL}/api/remandReport`,
  remandExtension: `${API_ARREST_BASE_URL}/api/remandExtension`,
  apprehensionReport: `${API_ARREST_BASE_URL}/api/apprehensionReport`,
  confessionalStatement: `${API_ARREST_BASE_URL}/api/confessionalStatement`,
  cclApprehension: `${API_ARREST_BASE_URL}/api/cclApprehension`,
  inquest: `${API_ARREST_BASE_URL}/api/inquest`,
  exhumation: `${API_ARREST_BASE_URL}/api/exhumation`,
  additionalMemo: `${API_ARREST_BASE_URL}/api/additionalMemo`,
  reOpeningOfCase: `${API_ARREST_BASE_URL}/api/reOpeningOfCase`,
  postmortem: `${API_ARREST_BASE_URL}/api/postmortem`,
  bailOppositions: `${API_ARREST_BASE_URL}/api/bailOppositions`,
  crpcNotice160: `${API_ARREST_BASE_URL}/api/160CRPC`,
  sec164CrPc: `${API_ARREST_BASE_URL}/api/164CRPC`,
  prosecutionPermission: `${API_ARREST_BASE_URL}/api/prosecutionPermission`,
  transferOfCaseFile: `${API_BASE_URL}/api/case/transferOfCase`,
  getTransferOfCaseFile: `${API_BASE_URL}/api/case/getTransferOfCase`,
  transferOfArrestCaseFile: `${API_ARREST_BASE_URL}/api/transferOfCase`,
  getTransferOfArrestCaseFile: `${API_ARREST_BASE_URL}/api/transferOfCase`,
  getReAssigningOfCase: `${API_ARREST_BASE_URL}/api/reAssigningOfCase`,
  createReAssigningOfCase: `${API_ARREST_BASE_URL}/api/reAssigningOfCase`,
  updateReAssigningOfCase: `${API_ARREST_BASE_URL}/api/reAssigningOfCase`,
  templatesUpload: `${API_ARREST_BASE_URL}/api/templates`,
  form54: `${API_ARREST_BASE_URL}/api/form54`,
  getReportedCases: `${API_BASE_URL}/api/reoprts/reportedCases`,
  getCasesStatus: `${API_BASE_URL}/api/reoprts/caseStatus`,
  getMissingCases: `${API_BASE_URL}/api/reoprts/missingCases`,
  getArrestedCases: `${API_BASE_URL}/api/reoprts/arrestDsr`,
  downloadReportedCases: `${API_BASE_URL}/api/reoprts/reportedCases/download`,
  downloadCasesStatus: `${API_BASE_URL}/api/reoprts/caseStatus/download`,
  downloadMissingCases: `${API_BASE_URL}/api/reoprts/missingCases/download`,
  downloadArrestedCases: `${API_BASE_URL}/api/reoprts/arrestDsr/download`,
  accidentInformationReport: `${API_BASE_URL}/api/reoprts/accidentInformationReport`,
  reportLogoFileId: `${REPORT_LOGO_FILE_ID}`,
  tableauReportUrl: `${API_TABLEAU_BASE_URL}/trusted`,
  reportedCasesUrl: `views/ReportedCases/ReportedCasesDB?[Parameters].[Parameter%205]=`,
  activityWiseReportUrl: `views/ActivityWiseReport/ActivityWiseReport?[Parameters].[Parameter%202]=`,
  accidentInformationReportUrl: `views/AccidentInformationReportDashboard/AIRDashboard?[Parameters].[Parameter%207]=`,
  actsAndSectionsUrl: `views/ActsandSectionsReport/ReportedCasesDB?[Parameters].[Parameter%205]=`,
  cdfReportUrl: `views/CDFDashboard_16765419173330/CDFDashboard?[Parameters].[Parameter%206]=`,
  itssoReportUrl: `views/ITSSOReportDashboard/ITSSODasboard?[Parameters].[Parameter%2010]=`,
  missingPersonReportUrl: `views/MissingPersonsReport/MissingPersonsDashboard?[Parameters].[Parameter%205]=`,
  zeroFirDashboard: `views/ZeroFIRDashboard/ZeroFIRDashboard?[Parameters].[Parameter%205]=`,
  onlineCrimeReviewTypeUrl: `views/ReportedCases_16776658203880/ReportedCasesDB_1?[Parameters].[Parameter%205]=`,
  crpcMajorHeadUrl: `views/CrPCMajorHeads/ReportedCasesDB?[Parameters].[Parameter%205]=`,
  sllMajorHeadUrl: `views/SLLMajorHeads/ReportedCasesDB?[Parameters].[Parameter%205]=`,
  crimesAgainestChildrenUrl: `views/CrimesAgainstChildren/CrimesAgainstChildren?[Parameters].[Parameter%205]=`,
  crimesAgainestSCSTUrl: `views/CrimesAgainstSCST/Dashboard?[Parameters].[Parameter%205]=`,
  crimesAgainestWomanUrl: `views/CrimesAgainstWomen/Dashboard?[Parameters].[Parameter%205]=`,
  fetchDropdownData: `${API_BASE_URL}/api/m_new/getTsHierarchyonLogin`,
  fetchGravecrimeData: `${API_BASE_URL}/api/higher-official/notificationDetails/v2`,
  fetchGraveCrimeList: `${API_BASE_URL}/api/dashboard/getRecentGraveFirList`,
  getCrimeAdvisory: `${API_BASE_URL}/api/m_new/getCrimeAdvisory`,
  getNotificationTo: `${API_BASE_URL}/api/m_new/getNotificationTo`,
  getGraveCrimeCount: `${API_BASE_URL}/api/higher-official/graveCrimesCount`,
  accusedArrestReportURL: `views/AccusedArrestReport/Dashboard?[Parameters].[Parameter%206]=`,
  AccusedsearchbasedonNameorBrieffactsUrl: `views/AccusedsearchbasedonNameorBrieffacts/Search?[Parameters].[Parameter%206]=`,
  ApplicationUsageStatisticsUrl: `views/ApplicationUsageStatistics-CCTNSV2/KPIDashboard?[Parameters].[Parameter%204]=`,
  DailyStatusReportUrl: `views/DailyStatusReport/Dashboard5?[Parameters].[Parameter%202]=`,
  DasboardVisualisationUrl: `views/DasboardVisualisation-ReportedCases/Dashboard?[Parameters].[Parameter%205]=`,
  MissingPersonsReportUrl: `views/MissingPersonsReport/MissingPersonsDashboard?[Parameters].[Parameter%205]=`,
  UnknownDeadBodyUrl: `views/UnknownDeadBody/Dashboard?[Parameters].[Parameter%205]=`,
  AnnexureVPTCasesStatus: `views/AnnexurePTFirDateCondition/Dashboard?[Parameters].[Parameter%205]=`,
  AnnexureIUICasesStatus: `views/AnnexureUI2/AnnexureUI?[Parameters].[Parameter%202]=`,
  CourtDisposals: `views/LokAdalatDisposalsDashboard/Dashboard?[Parameters].[Parameter%205]=`,
  CourtSummons: `views/CourtSummons/Dashboard?[Parameters].[Parameter%205]=`,
  CrimeWarrants: `views/Warrants/Dashboard?[Parameters].[Parameter%205]=`,
  OnlineCrimeReviewType1ALL: `views/OnlineCrimeReviewType1ALL/Dashboard?[Parameters].[Parameter%205]=`,
  CrimeReview: `views/CrimeReviewYearWise_16835284867950/Dashboard2?[Parameters].[Parameter%205]=`,
  getIoDetails: `${API_BASE_URL}/api/dashboard/getIoDetails`,
  RecentFirListDownloadToExcel: `${API_BASE_URL}/api/dashboard/getRecentFirListDownloadToExcel`,
  DownloadToExcelAdvisoryAndTransferOfCase: `${API_BASE_URL}/api/dashboard/downloadAdvisoryAndTransferOfCase`,
};

export default config;
 