const actions = {
  FETCH_INTERROGATION_REPORT_REQUEST: "FETCH_INTERROGATION_REPORT_REQUEST",
  FETCH_INTERROGATION_REPORT_SUCCESS: "FETCH_INTERROGATION_REPORT_SUCCESS",
  FETCH_INTERROGATION_REPORT_ERROR: "FETCH_INTERROGATION_REPORT_ERROR",

  ADD_INTERROGATION_REPORT_REQUEST: "ADD_INTERROGATION_REPORT_REQUEST",
  ADD_INTERROGATION_REPORT_SUCCESS: "ADD_INTERROGATION_REPORT_SUCCESS",
  ADD_INTERROGATION_REPORT_ERROR: "ADD_INTERROGATION_REPORT_ERROR",

  UPDATE_INTERROGATION_REPORT_REQUEST: "UPDATE_INTERROGATION_REPORT_REQUEST",
  UPDATE_INTERROGATION_REPORT_SUCCESS: "UPDATE_INTERROGATION_REPORT_SUCCESS",
  UPDATE_INTERROGATION_REPORT_ERROR: "UPDATE_INTERROGATION_REPORT_ERROR",

  UPDATE_PERSON_MEDIA_REQUEST: "UPDATE_PERSON_MEDIA_REQUEST",
  UPDATE_PERSON_MEDIA_SUCCESS: "UPDATE_PERSON_MEDIA_SUCCESS",
  UPDATE_PERSON_MEDIA_ERROR: "UPDATE_PERSON_MEDIA_ERROR",

  DELETE_REPORTS_REQUEST: "DELETE_REPORTS_REQUEST",
  DELETE_REPORTS_SUCCESS: "DELETE_REPORTS_SUCCESS",
  DELETE_REPORTS_ERROR: "DELETE_REPORTS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addInterrogationReportDetails: (url, body) => ({
    type: actions.ADD_INTERROGATION_REPORT_REQUEST,
    payload: { url, body },
  }),

  updateInterrogationReportDetails: (url, body) => ({
    type: actions.UPDATE_INTERROGATION_REPORT_REQUEST,
    payload: { url, body },
  }),

  getInterrogationReportList: (url) => ({
    type: actions.FETCH_INTERROGATION_REPORT_REQUEST,
    payload: { url },
  }),

  deleteInterrogationReport: (url, body) => ({
    type: actions.DELETE_REPORTS_REQUEST,
    payload: { url, body },
  }),

  updatePersonMedia: (url, body) => ({
    type: actions.UPDATE_PERSON_MEDIA_REQUEST,
    payload: { url, body },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
