const actions = {
  FETCH_ISSUE_OF_WARRANTS_REQUEST: "FETCH_ISSUE_OF_WARRANTS_REQUEST",
  FETCH_ISSUE_OF_WARRANTS_SUCCESS: "FETCH_ISSUE_OF_WARRANTS_SUCCESS",
  FETCH_ISSUE_OF_WARRANTS_ERROR: "FETCH_ISSUE_OF_WARRANTS_ERROR",

  ADD_ISSUE_OF_WARRANTS_REQUEST: "ADD_ISSUE_OF_WARRANTS_REQUEST",
  ADD_ISSUE_OF_WARRANTS_SUCCESS: "ADD_ISSUE_OF_WARRANTS_SUCCESS",
  ADD_ISSUE_OF_WARRANTS_ERROR: "ADD_ISSUE_OF_WARRANTS_ERROR",

  UPDATE_ISSUE_OF_WARRANTS_REQUEST: "UPDATE_ISSUE_OF_WARRANTS_REQUEST",
  UPDATE_ISSUE_OF_WARRANTS_SUCCESS: "UPDATE_ISSUE_OF_WARRANTS_SUCCESS",
  UPDATE_ISSUE_OF_WARRANTS_ERROR: "UPDATE_ISSUE_OF_WARRANTS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addIssueOfWarrants: (url, body) => ({
    type: actions.ADD_ISSUE_OF_WARRANTS_REQUEST,
    payload: { url, body },
  }),

  updateIssueOfWarrants: (url, body) => ({
    type: actions.UPDATE_ISSUE_OF_WARRANTS_REQUEST,
    payload: { url, body },
  }),

  getIssueOfWarrantsList: (url) => ({
    type: actions.FETCH_ISSUE_OF_WARRANTS_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
