const actions = {
  FETCH_SCIENTIFIC_EVIDENCE_REQUEST: "FETCH_SCIENTIFIC_EVIDENCE_REQUEST",
  FETCH_SCIENTIFIC_EVIDENCE_SUCCESS: "FETCH_SCIENTIFIC_EVIDENCE_SUCCESS",
  FETCH_SCIENTIFIC_EVIDENCE_ERROR: "FETCH_SCIENTIFIC_EVIDENCE_ERROR",

  ADD_SCIENTIFIC_EVIDENCE_REQUEST: "ADD_SCIENTIFIC_EVIDENCE_REQUEST",
  ADD_SCIENTIFIC_EVIDENCE_SUCCESS: "ADD_SCIENTIFIC_EVIDENCE_SUCCESS",
  ADD_SCIENTIFIC_EVIDENCE_ERROR: "ADD_SCIENTIFIC_EVIDENCE_ERROR",

  UPDATE_SCIENTIFIC_EVIDENCE_REQUEST: "UPDATE_SCIENTIFIC_EVIDENCE_REQUEST",
  UPDATE_SCIENTIFIC_EVIDENCE_SUCCESS: "UPDATE_SCIENTIFIC_EVIDENCE_SUCCESS",
  UPDATE_SCIENTIFIC_EVIDENCE_ERROR: "UPDATE_SCIENTIFIC_EVIDENCE_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addScientificEvidenceDetails: (url, body) => ({
    type: actions.ADD_SCIENTIFIC_EVIDENCE_REQUEST,
    payload: { url, body },
  }),

  updateScientificEvidenceDetails: (url, body) => ({
    type: actions.UPDATE_SCIENTIFIC_EVIDENCE_REQUEST,
    payload: { url, body },
  }),

  getScientificEvidenceList: (url) => ({
    type: actions.FETCH_SCIENTIFIC_EVIDENCE_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
