const actions = {
  FETCH_PROSECUTION_PERMISSION_REQUEST: "FETCH_PROSECUTION_PERMISSION_REQUEST",
  FETCH_PROSECUTION_PERMISSION_SUCCESS: "FETCH_PROSECUTION_PERMISSION_SUCCESS",
  FETCH_PROSECUTION_PERMISSION_ERROR: "FETCH_PROSECUTION_PERMISSION_ERROR",

  ADD_PROSECUTION_PERMISSION_REQUEST: "ADD_PROSECUTION_PERMISSION_REQUEST",
  ADD_PROSECUTION_PERMISSION_SUCCESS: "ADD_PROSECUTION_PERMISSION_SUCCESS",
  ADD_PROSECUTION_PERMISSION_ERROR: "ADD_PROSECUTION_PERMISSION_ERROR",

  UPDATE_PROSECUTION_PERMISSION_REQUEST:
    "UPDATE_PROSECUTION_PERMISSION_REQUEST",
  UPDATE_PROSECUTION_PERMISSION_SUCCESS:
    "UPDATE_PROSECUTION_PERMISSION_SUCCESS",
  UPDATE_PROSECUTION_PERMISSION_ERROR: "UPDATE_PROSECUTION_PERMISSION_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addProsecutionPermissionDetails: (url, body) => ({
    type: actions.ADD_PROSECUTION_PERMISSION_REQUEST,
    payload: { url, body },
  }),

  updateProsecutionPermissionDetails: (url, body) => ({
    type: actions.UPDATE_PROSECUTION_PERMISSION_REQUEST,
    payload: { url, body },
  }),

  getProsecutionPermissionList: (url) => ({
    type: actions.FETCH_PROSECUTION_PERMISSION_REQUEST,
    payload: { url },
  }),
  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
