const actions = {
  FETCH_APPREHENSION_REPORT_REQUEST: "FETCH_APPREHENSION_REPORT_REQUEST",
  FETCH_APPREHENSION_REPORT_SUCCESS: "FETCH_APPREHENSION_REPORT_SUCCESS",
  FETCH_APPREHENSION_REPORT_ERROR: "FETCH_APPREHENSION_REPORT_ERROR",

  ADD_APPREHENSION_REPORT_REQUEST: "ADD_APPREHENSION_REPORT_REQUEST",
  ADD_APPREHENSION_REPORT_SUCCESS: "ADD_APPREHENSION_REPORT_SUCCESS",
  ADD_APPREHENSION_REPORT_ERROR: "ADD_APPREHENSION_REPORT_ERROR",

  UPDATE_APPREHENSION_REPORT_REQUEST: "UPDATE_APPREHENSION_REPORT_REQUEST",
  UPDATE_APPREHENSION_REPORT_SUCCESS: "UPDATE_APPREHENSION_REPORT_SUCCESS",
  UPDATE_APPREHENSION_REPORT_ERROR: "UPDATE_APPREHENSION_REPORT_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addApprehensionReportDetails: (url, body) => ({
    type: actions.ADD_APPREHENSION_REPORT_REQUEST,
    payload: { url, body },
  }),

  updateApprehensionReportDetails: (url, body) => ({
    type: actions.UPDATE_APPREHENSION_REPORT_REQUEST,
    payload: { url, body },
  }),

  getApprehensionReportList: (url) => ({
    type: actions.FETCH_APPREHENSION_REPORT_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
