const actions = {
  FETCH_FIR_REQUEST: "FETCH_FIR_REQUEST",
  FETCH_FIR_SUCCESS: "FETCH_FIR_SUCCESS",
  FETCH_FIR_ERROR: "FETCH_FIR_ERROR",

  FETCH_HIGHERFIR_REQUEST: "FETCH_HIGHERFIR_REQUEST",
  FETCH_HIGHERFIR_SUCCESS: "FETCH_HIGHERFIR_SUCCESS",
  FETCH_HIGHERFIR_ERROR: "FETCH_HIGHERFIR_ERROR",

  FETCH_CASE_METRICS_REQUEST: "FETCH_CASE_METRICS_REQUEST",
  FETCH_CASE_METRICS_SUCCESS: "FETCH_CASE_METRICS_SUCCESS",
  FETCH_CASE_METRICS_ERROR: "FETCH_CASE_METRICS_ERROR",

  FETCH_RECENTFIRNUM_REQUEST: "FETCH_RECENTFIRNUM_REQUEST",
  FETCH_RECENTFIRNUM_SUCCESS: "FETCH_RECENTFIRNUM_SUCCESS",
  FETCH_RECENTFIRNUM_ERROR: "FETCH_RECENTFIRNUM_ERROR",

  DASHBOARD_URL_UPDATE: "DASHBOARD_URL_UPDATE",
  DASHBOARD_TOP_BAR_UPDATE: "DASHBOARD_TOP_BAR_UPDATE",

  UPDATE_SELECTED_WIDGET: "UPDATE_SELECTED_WIDGET",
  UPDATE_PS_CODE: "UPDATE_PS_CODE:",
  SET_DATE_FILTER: "SET_DATE_FILTER",
  UPDATE_SELECTED_CRIME_SCENE_DATE: "UPDATE_SELECTED_CRIME_SCENE_DATE",

  CHECK_IS_ON_CHANGE: "CHECK_IS_ON_CHANGE",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  FETCH_PRECRIMECASE_REQUEST: "FETCH_PRECRIMECASE_REQUEST",
  FETCH_PRECRIMECASE_SUCCESS: "FETCH_PRECRIMECASE_SUCCESS",
  FETCH_PRECRIMECASE_ERROR: "FETCH_PRECRIMECASE_ERROR",

  PRECRIMECASE_UPDATE_REQUEST: "PRECRIMECASE_UPDATE_REQUEST",
  PRECRIMECASE_UPDATE_SUCCESS: "PRECRIMECASE_UPDATE_SUCCESS",
  PRECRIMECASE_UPDATE_ERROR: "PRECRIMECASE_UPDATE_ERROR",

  CRIMELOCATION_UPDATE_REQUEST: "CRIMELOCATION_UPDATE_REQUEST",
  CRIMELOCATION_UPDATE_SUCCESS: "CRIMELOCATION_UPDATE_SUCCESS",
  CRIMELOCATION_UPDATE_ERROR: "CRIMELOCATION_UPDATE_ERROR",

  CRIMELOCATION_CREATE_REQUEST: "CRIMELOCATION_CREATE_REQUEST",
  CRIMELOCATION_CREATE_SUCCESS: "CRIMELOCATION_CREATE_SUCCESS",
  CRIMELOCATION_CREATE_ERROR: "CRIMELOCATION_CREATE_ERROR",

  CRIMECLASSIFICATION_UPDATE_REQUEST: "CRIMECLASSIFICATION_UPDATE_REQUEST",
  CRIMECLASSIFICATION_UPDATE_SUCCESS: "CRIMECLASSIFICATION_UPDATE_SUCCESS",
  CRIMECLASSIFICATION_UPDATE_ERROR: "CRIMECLASSIFICATION_UPDATE_ERROR",

  CASEPROPERTYMANAGEMENT_UPDATE_REQUEST:
    "CASEPROPERTYMANAGEMENT_UPDATE_REQUEST",
  CASEPROPERTYMANAGEMENT_UPDATE_SUCCESS:
    "CASEPROPERTYMANAGEMENT_UPDATE_SUCCESS",
  CASEPROPERTYMANAGEMENT_UPDATE_ERROR: "CASEPROPERTYMANAGEMENT_UPDATE_ERROR",

  PANCHWITNESS_UPDATE_REQUEST: "PANCHWITNESS_UPDATE_REQUEST",
  PANCHWITNESS_UPDATE_SUCCESS: "PANCHWITNESS_UPDATE_SUCCESS",
  PANCHWITNESS_UPDATE_ERROR: "PANCHWITNESS_UPDATE_ERROR",

  PANCHWITNESS_EDIT_REQUEST: "PANCHWITNESS_EDIT_REQUEST",
  PANCHWITNESS_EDIT_SUCCESS: "PANCHWITNESS_EDIT_SUCCESS",
  PANCHWITNESS_EDIT_ERROR: "PANCHWITNESS_EDIT_ERROR",

  WITNESS_UPDATE_REQUEST: "WITNESS_UPDATE_REQUEST",
  WITNESS_UPDATE_SUCCESS: "WITNESS_UPDATE_SUCCESS",
  WITNESS_UPDATE_ERROR: "WITNESS_UPDATE_ERROR",

  PERSON_MEDIA_UPDATE_REQUEST: "PERSON_MEDIA_UPDATE_REQUEST",
  PERSON_MEDIA_UPDATE_SUCCESS: "PERSON_MEDIA_UPDATE_SUCCESS",
  PERSON_MEDIA_UPDATE_ERROR: "PERSON_MEDIA_UPDATE_ERROR",

  ROUGHSKETCH_UPDATE_REQUEST: "ROUGHSKETCH_UPDATE_REQUEST",
  ROUGHSKETCH_UPDATE_SUCCESS: "ROUGHSKETCH_UPDATE_SUCCESS",
  ROUGHSKETCH_UPDATE_ERROR: "ROUGHSKETCH_UPDATE_ERROR",

  WITNESS_EDIT_REQUEST: "WITNESS_EDIT_REQUEST",
  WITNESS_EDIT_SUCCESS: "WITNESS_EDIT_SUCCESS",
  WITNESS_EDIT_ERROR: "WITNESS_EDIT_ERROR",

  MATERIALOBJECT_UPDATE_REQUEST: "MATERIALOBJECT_UPDATE_REQUEST",
  MATERIALOBJECT_UPDATE_SUCCESS: "MATERIALOBJECT_UPDATE_SUCCESS",
  MATERIALOBJECT_UPDATE_ERROR: "MATERIALOBJECT_UPDATE_ERROR",

  MATERIALOBJECT_EDIT_REQUEST: "MATERIALOBJECT_EDIT_REQUEST",
  MATERIALOBJECT_EDIT_SUCCESS: "MATERIALOBJECT_EDIT_SUCCESS",
  MATERIALOBJECT_EDIT_ERROR: "MATERIALOBJECT_EDIT_ERROR",

  EXPERTTEAM_UPDATE_REQUEST: "EXPERTTEAM_UPDATE_REQUEST",
  EXPERTTEAM_UPDATE_SUCCESS: "EXPERTTEAM_UPDATE_SUCCESS",
  EXPERTTEAM_UPDATE_ERROR: "EXPERTTEAM_UPDATE_ERROR",

  EXPERTTEAM_ADD_REQUEST: "EXPERTTEAM_ADD_REQUEST",
  EXPERTTEAM_ADD_SUCCESS: "EXPERTTEAM_ADD_SUCCESS",
  EXPERTTEAM_ADD_ERROR: "EXPERTTEAM_ADD_ERROR",

  FETCH_EXPERTTEAM_REQUEST: "FETCH_EXPERTTEAM_REQUEST",
  FETCH_EXPERTTEAM_SUCCESS: "FETCH_EXPERTTEAM_SUCCESS",
  FETCH_EXPERTTEAM_ERROR: "FETCH_EXPERTTEAM_ERROR",

  FETCH_WITNESSSTATEMENT_REQUEST: "FETCH_WITNESSSTATEMENT_REQUEST",
  FETCH_WITNESSSTATEMENT_SUCCESS: "FETCH_WITNESSSTATEMENT_SUCCESS",
  FETCH_WITNESSSTATEMENT_ERROR: "FETCH_WITNESSSTATEMENT_ERROR",

  FETCH_WITNESSSTATEMENT_NEW_REQUEST: "FETCH_WITNESSSTATEMENT_NEW_REQUEST",
  FETCH_WITNESSSTATEMENT_NEW_SUCCESS: "FETCH_WITNESSSTATEMENT_NEW_SUCCESS",
  FETCH_WITNESSSTATEMENT_NEW_ERROR: "FETCH_WITNESSSTATEMENT_NEW_ERROR",

  FETCH_PANCHWITNESS_REQUEST: "FETCH_PANCHWITNESS_REQUEST",
  FETCH_PANCHWITNESS_SUCCESS: "FETCH_PANCHWITNESS_SUCCESS",
  FETCH_PANCHWITNESS_ERROR: "FETCH_PANCHWITNESS_ERROR",

  FETCH_MATERIALOBJECT_REQUEST: "FETCH_MATERIALOBJECT_REQUEST",
  FETCH_MATERIALOBJECT_SUCCESS: "FETCH_MATERIALOBJECT_SUCCESS",
  FETCH_MATERIALOBJECT_ERROR: "FETCH_MATERIALOBJECT_ERROR",

  FETCH_CRIMELOCATION_REQUEST: "FETCH_CRIMELOCATION_REQUEST",
  FETCH_CRIMELOCATION_SUCCESS: "FETCH_CRIMELOCATION_SUCCESS",
  FETCH_CRIMELOCATION_ERROR: "FETCH_CRIMELOCATION_ERROR",

  FETCH_ROUGHSKETCH_REQUEST: "FETCH_ROUGHSKETCH_REQUEST",
  FETCH_ROUGHSKETCH_SUCCESS: "FETCH_ROUGHSKETCH_SUCCESS",
  FETCH_ROUGHSKETCH_ERROR: "FETCH_ROUGHSKETCH_ERROR",

  FETCH_CRIMECLASSIFICATION_REQUEST: "FETCH_CRIMECLASSIFICATION_REQUEST",
  FETCH_CRIMECLASSIFICATION_SUCCESS: "FETCH_CRIMECLASSIFICATION_SUCCESS",
  FETCH_CRIMECLASSIFICATION_ERROR: "FETCH_CRIMECLASSIFICATION_ERROR",

  GET_CRIMECLASSIFICATION_REQUEST: "GET_CRIMECLASSIFICATION_REQUEST",
  GET_CRIMECLASSIFICATION_SUCCESS: " GET_CRIMECLASSIFICATION_SUCCESS",
  GET_CRIMECLASSIFICATION_ERROR: " GET_CRIMECLASSIFICATION_ERROR",

  RESET_CRIMECLASSIFICATION: "RESET_CRIMECLASSIFICATION",

  FETCH_PRECRIMEHISTORY_REQUEST: "FETCH_PRECRIMEHISTORY_REQUEST",
  FETCH_PRECRIMEHISTORY_SUCCESS: "FETCH_PRECRIMEHISTORY_SUCCESS",
  FETCH_PRECRIMEHISTORY_ERROR: "FETCH_PRECRIMEHISTORY_ERROR",

  FETCH_CASEPROPERTYMANAGEMENT_REQUEST: "FETCH_CASEPROPERTYMANAGEMENT_REQUEST",
  FETCH_CASEPROPERTYMANAGEMENT_SUCCESS: "FETCH_CASEPROPERTYMANAGEMENT_SUCCESS",
  FETCH_CASEPROPERTYMANAGEMENT_ERROR: "FETCH_CASEPROPERTYMANAGEMENT_ERROR",

  FETCH_HISTORYOPTIONS_REQUEST: "FETCH_HISTORYOPTIONS_REQUEST",
  FETCH_HISTORYOPTIONS_SUCCESS: "FETCH_HISTORYOPTIONS_SUCCESS",
  FETCH_HISTORYOPTIONS_ERROR: "FETCH_HISTORYOPTIONS_ERROR",

  ARREST_UPDATE_REQUEST: "ARREST_UPDATE_REQUEST",
  ARREST_UPDATE_SUCCESS: "ARREST_UPDATE_SUCCESS",
  ARREST_UPDATE_ERROR: "ARREST_UPDATE_ERROR",

  ARREST_CREATE_REQUEST: "ARREST_CREATE_REQUEST",
  ARREST_CREATE_SUCCESS: "ARREST_CREATE_SUCCESS",
  ARREST_CREATE_ERROR: "ARREST_CREATE_ERROR",

  FETCH_ARREST_REQUEST: "FETCH_ARREST_REQUEST",
  FETCH_ARREST_SUCCESS: "FETCH_ARREST_SUCCESS",
  FETCH_ARREST_ERROR: "FETCH_ARREST_ERROR",

  UPDATE_WITNESS_ORDER_REQUEST: "UPDATE_WITNESS_ORDER_REQUEST",
  UPDATE_WITNESS_ORDER_SUCCESS: "UPDATE_WITNESS_ORDER_SUCCESS",
  UPDATE_WITNESS_ORDER_ERROR: "UPDATE_WITNESS_ORDER_ERROR",

  GET_COMPLAINANT_DETAILS_REQUEST: "GET_COMPLAINANT_DETAILS_REQUEST",
  GET_COMPLAINANT_DETAILS_SUCCESS: "GET_COMPLAINANT_DETAILS_SUCCESS",
  GET_COMPLAINANT_DETAILS_ERROR: "GET_COMPLAINANT_DETAILS_ERROR",

  RESET_WITNESS_ORDER_ACTIONTYPE: "RESET_WITNESS_ORDER_ACTIONTYPE",

  FETCH_CRIME_SCENE_PHOTOGRAPHS_REQUEST:
    "FETCH_CRIME_SCENE_PHOTOGRAPHS_REQUEST",
  FETCH_CRIME_SCENE_PHOTOGRAPHS_SUCCESS:
    "FETCH_CRIME_SCENE_PHOTOGRAPHS_SUCCESS",
  FETCH_CRIME_SCENE_PHOTOGRAPHS_ERROR: "FETCH_CRIME_SCENE_PHOTOGRAPHS_ERROR",

  UPDATE_CRIME_SCENE_PHOTOGRAPHS_REQUEST:
    "UPDATE_CRIME_SCENE_PHOTOGRAPHS_REQUEST",
  UPDATE_CRIME_SCENE_PHOTOGRAPHS_SUCCESS:
    "UPDATE_CRIME_SCENE_PHOTOGRAPHS_SUCCESS",
  UPDATE_CRIME_SCENE_PHOTOGRAPHS_ERROR: "UPDATE_CRIME_SCENE_PHOTOGRAPHS_ERROR",

  FETCH_PROFESSIONALLIST_REQUEST: "FETCH_PROFESSIONALLIST_REQUEST",
  FETCH_PROFESSIONALLIST_SUCCESS: "FETCH_PROFESSIONALLIST_SUCCESS",
  FETCH_PROFESSIONALLIST_ERROR: "FETCH_PROFESSIONALLIST_ERROR",

  FETCH_TRANSFERRED_ZERO_FIR_HISTORY_REQUEST:
    "FETCH_TRANSFERRED_ZERO_FIR_HISTORY_REQUEST",
  FETCH_TRANSFERRED_ZERO_FIR_HISTORY_SUCCESS:
    "FETCH_TRANSFERRED_ZERO_FIR_HISTORY_SUCCESS",
  FETCH_TRANSFERRED_ZERO_FIR_HISTORY_ERROR:
    "FETCH_TRANSFERRED_ZERO_FIR_HISTORY_ERROR",

  FETCH_RECEIVED_ZERO_FIR_HISTORY_REQUEST:
    "FETCH_RECEIVED_ZERO_FIR_HISTORY_REQUEST",
  FETCH_RECEIVED_ZERO_FIR_HISTORY_SUCCESS:
    "FETCH_RECEIVED_ZERO_FIR_HISTORY_SUCCESS",
  FETCH_RECEIVED_ZERO_FIR_HISTORY_ERROR:
    "FETCH_RECEIVED_ZERO_FIR_HISTORY_ERROR",

  FETCH_APPROVAL_FIR_REQUEST: "FETCH_APPROVAL_FIR_REQUEST",
  FETCH_APPROVAL_SUCCESS: "FETCH_APPROVAL_SUCCESS",
  FETCH_APPROVAL_ERROR: "FETCH_APPROVAL_ERROR",

  FETCH_DROPDOWNDATA_REQUEST: "FETCH_DROPDOWNDATA_REQUEST",
  FETCH_DROPDOWNDATA_SUCCESS: "FETCH_DROPDOWNDATA_SUCCESS",
  FETCH_DROPDOWNDATA_ERROR: "FETCH_DROPDOWNDATA_ERROR",

  FETCH_GRAVECRIMEDATA_REQUEST: "FETCH_GRAVECRIMEDATA_REQUEST",
  FETCH_GRAVECRIMEDATA_SUCCESS: "FETCH_GRAVECRIMEDATA_SUCCESS",
  FETCH_GRAVECRIMEDATA_ERROR: "FETCH_GRAVECRIMEDATA_ERROR",

  FETCH_GRAVECRIMELIST_REQUEST: "FETCH_GRAVECRIMELIST_REQUEST",
  FETCH_GRAVECRIMELIST_SUCCESS: "FETCH_GRAVECRIMELIST_SUCCESS",
  FETCH_GRAVECRIMELIST_ERROR: "FETCH_GRAVECRIMELIST_ERROR",
  RESET_DROPDOWNDATA: "RESET_DROPDOWNDATA",
  SET_BETWEEN_DATES: "SET_BETWEEN_DATES",

  FETCH_GRAVECRIMECOUNT_REQUEST: "FETCH_GRAVECRIMECOUNT_REQUEST",
  FETCH_GRAVECRIMECOUNT_SUCCESS: "FETCH_GRAVECRIMECOUNT_SUCCESS",
  FETCH_GRAVECRIMECOUNT_ERROR: "FETCH_GRAVECRIMECOUNT_ERROR",

  SET_SELECTED_YEAR: "SET_SELECTED_YEAR",

  fetchTransferredZeroFIRHistory: (url) => ({
    type: actions.FETCH_TRANSFERRED_ZERO_FIR_HISTORY_REQUEST,
    payload: { url },
  }),

  fetchReceivedZeroFIRHistory: (url) => ({
    type: actions.FETCH_RECEIVED_ZERO_FIR_HISTORY_REQUEST,
    payload: { url },
  }),

  fetchFIRList: (url) => ({
    type: actions.FETCH_FIR_REQUEST,
    payload: { url },
  }),

  fetchApprovalFIRList: (url) => ({
    type: actions.FETCH_APPROVAL_FIR_REQUEST,
    payload: { url },
  }),

  fetchRecentFIRNumList: (url) => ({
    type: actions.FETCH_RECENTFIRNUM_REQUEST,
    payload: { url },
  }),

  fetchCrimeLocation: (url) => ({
    type: actions.FETCH_CRIMELOCATION_REQUEST,
    payload: { url },
  }),

  fetchArrest: (url) => ({
    type: actions.FETCH_ARREST_REQUEST,
    payload: { url },
  }),

  fetchCrimeClassification: (url) => ({
    type: actions.FETCH_CRIMECLASSIFICATION_REQUEST,
    payload: { url },
  }),

  getCrimeClassification: (url) => ({
    type: actions.GET_CRIMECLASSIFICATION_REQUEST,
    payload: { url },
  }),

  fetchCasePropertyManagement: (url) => ({
    type: actions.FETCH_CASEPROPERTYMANAGEMENT_REQUEST,
    payload: { url },
  }),

  fetchPreCrimeCase: (url) => ({
    type: actions.FETCH_PRECRIMECASE_REQUEST,
    payload: { url },
  }),

  fetchMaterialObjectList: (url) => ({
    type: actions.FETCH_MATERIALOBJECT_REQUEST,
    payload: { url },
  }),

  fetchWitnessDetailsList: (url) => ({
    type: actions.FETCH_WITNESSSTATEMENT_REQUEST,
    payload: { url },
  }),

  fetchWitnessStatementsList: (url) => ({
    type: actions.FETCH_WITNESSSTATEMENT_NEW_REQUEST,
    payload: { url },
  }),

  fetchPanchWitnessList: (url) => ({
    type: actions.FETCH_PANCHWITNESS_REQUEST,
    payload: { url },
  }),

  fetchExpertTeamList: (url) => ({
    type: actions.FETCH_EXPERTTEAM_REQUEST,
    payload: { url },
  }),

  fetchRoughSketchList: (url) => ({
    type: actions.FETCH_ROUGHSKETCH_REQUEST,
    payload: { url },
  }),

  updateDashboardTopBar: (value) => {
    return {
      type: actions.DASHBOARD_URL_UPDATE,
      isCustomTopBar: value,
    };
  },

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
  resetDropdown: () => {
    return {
      type: actions.RESET_DROPDOWNDATA,
    };
  },

  resetCrimeClassification: () => {
    return {
      type: actions.RESET_CRIMECLASSIFICATION,
    };
  },

  resetCrimeClassification: () => {
    return {
      type: actions.RESET_CRIMECLASSIFICATION,
    };
  },

  resetCrimeClassification: () => {
    return {
      type: actions.RESET_CRIMECLASSIFICATION,
    };
  },

  updateDashboardData: (value) => {
    return {
      type: actions.DASHBOARD_TOP_BAR_UPDATE,
      isDashboard: value,
    };
  },

  updateSelectedWidget: (value) => {
    return {
      type: actions.UPDATE_SELECTED_WIDGET,
      selectedWidgetStatus: value,
    };
  },

  updateSelectedCrimeSceneDate: (value) => {
    return {
      type: actions.UPDATE_SELECTED_CRIME_SCENE_DATE,
      selectedCrimeSceneDate: value,
    };
  },

  updateSelection: (value) => {
    return {
      type: actions.CHECK_IS_ON_CHANGE,
      isOnChange: value,
    };
  },

  updatePrecrimeCase: (url, body) => ({
    type: actions.PRECRIMECASE_UPDATE_REQUEST,
    payload: { url, body },
  }),

  updateCrimeLocation: (url, body) => ({
    type: actions.CRIMELOCATION_UPDATE_REQUEST,
    payload: { url, body },
  }),

  createCrimeLocation: (url, body) => ({
    type: actions.CRIMELOCATION_CREATE_REQUEST,
    payload: { url, body },
  }),

  updatePunchWitness: (url, body) => ({
    type: actions.PANCHWITNESS_UPDATE_REQUEST,
    payload: { url, body },
  }),

  editPunchWitness: (url, body) => ({
    type: actions.PANCHWITNESS_EDIT_REQUEST,
    payload: { url, body },
  }),

  updateWitnessStatement: (url, body) => ({
    type: actions.WITNESS_UPDATE_REQUEST,
    payload: { url, body },
  }),

  updatePersonMediaDetails: (url, body) => ({
    type: actions.PERSON_MEDIA_UPDATE_REQUEST,
    payload: { url, body },
  }),

  editWitnessStatement: (url, body) => ({
    type: actions.WITNESS_UPDATE_REQUEST,
    payload: { url, body },
  }),

  updateRoughSketch: (url, body) => ({
    type: actions.ROUGHSKETCH_UPDATE_REQUEST,
    payload: { url, body },
  }),

  createMaterialObject: (url, body) => ({
    type: actions.MATERIALOBJECT_UPDATE_REQUEST,
    payload: { url, body },
  }),

  editMaterialObject: (url, body) => ({
    type: actions.MATERIALOBJECT_EDIT_REQUEST,
    payload: { url, body },
  }),

  addExpertTeam: (url, body) => ({
    type: actions.EXPERTTEAM_ADD_REQUEST,
    payload: { url, body },
  }),

  updateExpertTeam: (url, body) => ({
    type: actions.EXPERTTEAM_UPDATE_REQUEST,
    payload: { url, body },
  }),

  addUpdateCrimeClassification: (url, body) => ({
    type: actions.CRIMECLASSIFICATION_UPDATE_REQUEST,
    payload: { url, body },
  }),

  updateCasePropertyManagement: (url, body) => ({
    type: actions.CASEPROPERTYMANAGEMENT_UPDATE_REQUEST,
    payload: { url, body },
  }),

  fetchPreCrimeHistory: (url) => ({
    type: actions.FETCH_PRECRIMEHISTORY_REQUEST,
    payload: { url },
  }),

  fetchHistoryOptions: (url) => ({
    type: actions.FETCH_HISTORYOPTIONS_REQUEST,
    payload: { url },
  }),

  updateArrest: (url, body) => ({
    type: actions.ARREST_UPDATE_REQUEST,
    payload: { url, body },
  }),

  createArrest: (url, body) => ({
    type: actions.ARREST_CREATE_REQUEST,
    payload: { url, body },
  }),

  updateWitnessOrder: (url, body) => ({
    type: actions.UPDATE_WITNESS_ORDER_REQUEST,
    payload: { url, body },
  }),

  fetchComplainantList: (url) => ({
    type: actions.GET_COMPLAINANT_DETAILS_REQUEST,
    payload: { url },
  }),

  resetWitnessOrderActionType: () => {
    return {
      type: actions.RESET_WITNESS_ORDER_ACTIONTYPE,
    };
  },

  fetchCrimeScenePhotographsList: (url) => ({
    type: actions.FETCH_CRIME_SCENE_PHOTOGRAPHS_REQUEST,
    payload: { url },
  }),

  updateCrimeScenePhotographsList: (url, body) => ({
    type: actions.UPDATE_CRIME_SCENE_PHOTOGRAPHS_REQUEST,
    payload: { url, body },
  }),

  fetchProfessionalList: (url) => ({
    type: actions.FETCH_PROFESSIONALLIST_REQUEST,
    payload: { url },
  }),
  fetchDropdownData: (url, body) => ({
    type: actions.FETCH_DROPDOWNDATA_REQUEST,
    payload: { url, body },
  }),
  fetchHigherFIRList: (url) => ({
    type: actions.FETCH_HIGHERFIR_REQUEST,
    payload: { url },
  }),
  fetchCaseMetrics: (url) => ({
    type: actions.FETCH_CASE_METRICS_REQUEST,
    payload: { url },
  }),
  fetchGravecrimeData: (url, body) => ({
    type: actions.FETCH_GRAVECRIMEDATA_REQUEST,
    payload: { url, body },
  }),
  updatePsCode: (value) => ({
    type: actions.UPDATE_PS_CODE,
    updatedPsCode: value,
  }),
  getGraveList: (url, body) => ({
    type: actions.FETCH_GRAVECRIMELIST_REQUEST,
    payload: { url, body },
  }),
  getbetweenDates: (value) => ({
    type: actions.SET_BETWEEN_DATES,
    betweenDates: value,
  }),
  getGraveCrimeCount: (url, body) => ({
    type: actions.FETCH_GRAVECRIMECOUNT_REQUEST,
    payload: { url, body },
  }),
  getselectedYear: (value) => ({
    type: actions.SET_SELECTED_YEAR,
    setSelectedYear: value,
  }),
};
export default actions;
