export const summonToList = [
  { label: "Accused" },
  { label: "Witness" },
  { label: "IO" },
  { label: "SHO" },
];

export const listOfWarrantType = [
  { label: "Bailable" },
  { label: "Non bailable" },
  { label: "LPC" },
];

export const presentOrNotList = [
  { label: "Present" },
  { label: "Not Present" },
];

export const disposalList = [
  { label: "Convicted" },
  { label: "Action Abated" },
  { label: "Acquittal" },
  { label: "Compromised" },
  { label: "Discharged" },
  { label: "Quashed" },
  { label: "Withdrawal of Prosecution" },
  { label: "Compounded" },
];

export const appealPreferredList = [
  { label: "Accused" },
  { label: "Complainant" },
  { label: "State" },
];

export const confirmationList = [{ label: "Yes" }, { label: "No" }];

export const examinationStatusList = [
  { label: "Bind over" },
  { label: "Examination Completed" },
  { label: "Given up" },
  { label: "Not Examined" },
  { label: "On-going Examination" },
];

export const otherFormsList = [
  { label: "Issue of Warrants" },
  { label: "Proclamation" },
  { label: "Notice to Surety" },
];

export const judgementList = [
  { label: "Acquitted" },
  { label: "Convicted" },
  { label: "Compounded" },
];

export const argumentTypeList = [{ label: "Oral" }, { label: "Written" }];

export const genderList = [
  { label: "Eunuch" },
  { label: "Female" },
  { label: "Human Skeleton" },
  { label: "Male" },
  { label: "Transgender" },
];

export const occupationList = [
  { label: "Academician" },
  { label: "Accountant" },
  { label: "Advocate" },
  { label: "Advocate/Law Practitioner" },
  { label: "Agent" },
  { label: "Air Lines Staff" },
  { label: "Airport Staff" },
  { label: "Architect" },
  { label: "Artisan" },
  { label: "Artist" },
  { label: "Asst. Supervisor" },
  { label: "Bank Employee" },
  { label: "Barber" },
  { label: "Beggar" },
  { label: "Black Smith" },
  { label: "Bootlegger" },
  { label: "Broker" },
  { label: "Builder" },
  { label: "Bullock Cart Driver" },
  { label: "Bus Conductor" },
  { label: "Business" },
  { label: "Cable Operators" },
  { label: "Carpenter" },
  { label: "Chairman" },
  { label: "Civil Supplier" },
  { label: "Cleaner Bus" },
  { label: "Cleaner Truck" },
  { label: "Cobbler" },
  { label: "Company Executive" },
  { label: "Computer Professional" },
  { label: "Contractor" },
  { label: "Cook" },
  { label: "Courier" },
  { label: "Craftsman" },
  { label: "Crew" },
  { label: "Dealer - Antique" },
  { label: "Dealer - Skin & Fur" },
  { label: "Defence Personnel" },
  { label: "Doctor" },
  { label: "Domestic Servant" },
  { label: "Draughtsman" },
  { label: "Driver" },
  { label: "Driver - Bus" },
  { label: "Driver - Car" },
  { label: "Driver - Cart" },
  { label: "Driver - Taxi" },
  { label: "Driver - Truck" },
  { label: "Driver-Autorickshaw" },
  { label: "Drug Trafficker" },
  { label: "Elected Representatives" },
  { label: "Electrician" },
  { label: "Employed in Private Firms" },
  { label: "Engineers" },
  { label: "Exporter" },
  { label: "Factory Worker" },
  { label: "Farmer" },
  { label: "Financier" },
  { label: "Fireman" },
  { label: "Fisherman" },
  { label: "Gambler" },
  { label: "Gardner" },
  { label: "Gold Smith" },
  { label: "Govt. official Gazetted" },
  { label: "Govt. official Non-Gazetted" },
  { label: "Hawkers" },
  { label: "Helper" },
  { label: "Hired Killer" },
  { label: "Home-Guard" },
  { label: "Hotel Employee" },
  { label: "House Help - Hired" },
  { label: "Housewife" },
  { label: "Importer" },
  { label: "Industrialist" },
  { label: "Jail Staff" },
  { label: "Judicial officer" },
  { label: "Jugglers" },
  { label: "Labourer" },
  { label: "Launderer (Dhobi)" },
  { label: "Lineman" },
  { label: "Literary Person" },
  { label: "MRO" },
  { label: "Manager" },
  { label: "Mason" },
  { label: "Mechanic" },
  { label: "Media Person" },
  { label: "Medical Practitioner" },
  { label: "Mercenary" },
  { label: "Milkman" },
  { label: "Mines Employee" },
  { label: "Money Lender" },
  { label: "NGOs Employee" },
  { label: "Nomad" },
  { label: "Painter" },
  { label: "Panchayath Secretery" },
  { label: "Para Medical Staff" },
  { label: "Peon" },
  { label: "Photographer" },
  { label: "Pilot" },
  { label: "Pimp" },
  { label: "Plumber" },
  { label: "Police officer" },
  { label: "Politicians" },
  { label: "Porter" },
  { label: "Postal Staff" },
  { label: "Private Employee" },
  { label: "Professor" },
  { label: "Prosecutor" },
  { label: "Prostitute" },
  { label: "Railways Staff" },
  { label: "Real Estate Dealer" },
  { label: "Relative/Friend" },
  { label: "Religious Person" },
  { label: "Retired Employee" },
  { label: "Retired Govt. Employee" },
  { label: "Rickshaw Puller" },
  { label: "Salesman" },
  { label: "Sanitary Worker" },
  { label: "Security Guard" },
  { label: "Servant" },
  { label: "Servant maid" },
  { label: "Shop Employee" },
  { label: "Shopkeeper" },
  { label: "Smuggler" },
  { label: "Social Service" },
  { label: "Sports Person" },
  { label: "Student" },
  { label: "Supervisor" },
  { label: "Surveyor" },
  { label: "Sweeper" },
  { label: "Tailor" },
  { label: "Tally Clerk" },
  { label: "Teacher" },
  { label: "Technician" },
  { label: "Telecom Staff" },
  { label: "Tourist" },
  { label: "Tractor Driver" },
  { label: "Trader" },
  { label: "Travelling as Co-Passenger" },
  { label: "Unemployed" },
  { label: "Utility Serivceman" },
  { label: "VRA" },
  { label: "VRO" },
  { label: "Vagabond" },
  { label: "Vendor" },
  { label: "Video Exhibitors" },
  { label: "Watchman" },
  { label: "Weaver" },
  { label: "Welder" },
  { label: "Working in CPO/Para Military Organization" },
];

export const rankNameList = [
  { label: "Additional Public Prosecutor" },
  { label: "Assistant Public Prosecutor" },
  { label: "Attorney General" },
  { label: "Director" },
  { label: "Gp-Civil" },
  { label: "Gp-Criminal" },
  { label: "Gp-Tribunal" },
  { label: "Joint Director" },
  { label: "Public Prosecutor" },
];

export const proclamationData = [
  "Collected Property Details from Revenue Department Officials",
  "Collected Property Details of Accused",
  "Proclamation affixed to the conspicuous part of the house of Accused",
  "Proclamation affixed to the conspicuous part of the Court-House",
  "Proclamation signed by Head/Witness of area where accused resides",
  "Proclamation publicly read in the conspicuous place of accused ",
  "Published and affixed in Public Places",
  "Published in Local News Paper",
  "Others",
];

export const reasonForTransferList = [
  { label: "Case & Counter" },
  { label: "Over burden" },
  { label: "Point of Jurisdiction" },
  { label: "Request by Complainant" },
  { label: "Request by Victim" },
  { label: "Request by Accused" },
  { label: "Others" },
];

export const statusList = [
  { label: "Executed" },
  { label: "Pending" },
  { label: "Returned to Court" },
];

export const pendingReason = [
  { label: "Address not Traced" },
  { label: "Death of the Person" },
  { label: "House Locked" },
  { label: "Others" },
];

export const returningReason = [
  { label: "Expiry Date" },
  { label: "N B W issued" },
  { label: "Notice to sureties" },
  { label: "Forfeiture of sureties" },
  { label: "82 Cr.P.C. proclamation" },
  { label: "83 Cr.P.C. attachment of property" },
  { label: "Returned after Execution" },
  { label: "Others" },
];

export const typeOfProperty = [{ label: "Money" }, { label: "Property" }];
