const actions = {
  FETCH_AUDIO_VIDEO_CLIPPINGS_REQUEST: "FETCH_AUDIO_VIDEO_CLIPPINGS_REQUEST",
  FETCH_AUDIO_VIDEO_CLIPPINGS_SUCCESS: "FETCH_AUDIO_VIDEO_CLIPPINGS_SUCCESS",
  FETCH_AUDIO_VIDEO_CLIPPINGS_ERROR: "FETCH_AUDIO_VIDEO_CLIPPINGS_ERROR",

  ADD_AUDIO_VIDEO_CLIPPINGS_REQUEST: "ADD_AUDIO_VIDEO_CLIPPINGS_REQUEST",
  ADD_AUDIO_VIDEO_CLIPPINGS_SUCCESS: "ADD_AUDIO_VIDEO_CLIPPINGS_SUCCESS",
  ADD_AUDIO_VIDEO_CLIPPINGS_ERROR: "ADD_AUDIO_VIDEO_CLIPPINGS_ERROR",

  UPDATE_AUDIO_VIDEO_CLIPPINGS_REQUEST: "UPDATE_AUDIO_VIDEO_CLIPPINGS_REQUEST",
  UPDATE_AUDIO_VIDEO_CLIPPINGS_SUCCESS: "UPDATE_AUDIO_VIDEO_CLIPPINGS_SUCCESS",
  UPDATE_AUDIO_VIDEO_CLIPPINGS_ERROR: "UPDATE_AUDIO_VIDEO_CLIPPINGS_ERROR",

  RESET_ACTIONTYPE: "RESET_ACTIONTYPE",

  addAudioVideoClippingDetails: (url, body) => ({
    type: actions.ADD_AUDIO_VIDEO_CLIPPINGS_REQUEST,
    payload: { url, body },
  }),

  updateAudioVideoClippingDetails: (url, body) => ({
    type: actions.UPDATE_AUDIO_VIDEO_CLIPPINGS_REQUEST,
    payload: { url, body },
  }),

  getAudioVideoClippingList: (url) => ({
    type: actions.FETCH_AUDIO_VIDEO_CLIPPINGS_REQUEST,
    payload: { url },
  }),

  resetActionType: () => {
    return {
      type: actions.RESET_ACTIONTYPE,
    };
  },
};
export default actions;
